[#9] 피드 조회, 태그기능
f-lab-edu/Stoury pull request #10
Opened 2024-01-21 04:37 UTC by jzakka

## 기능
- 사용자가 작성한 피드를 페이지네이션해서 조회
- 특정 태그의 피드를 페이지네이션해서 조회
- 피드 생성할 때, 여러개의 태그 지정 가능. 이미 존재하는 태그여도 되고 존재하지 않으면 피드 생성과 동시에 태그도 함께 생성

## 변경
- 피드 입력시 태그를 함께 받도록 수정
- 피드 단위 테스트와 통합 테스트를 분리
- 피드의 생성날짜에 인덱스 설정
- 국가 이름을 열거형으로 생성

2024-01-22 07:07 UTC, jzakka commented on src/main/java/com/stoury/service/TagService.java
> +public class TagService {
FeedService에서 FeedRequest의 태그를 조회하거나 생성하는 게 FeedService의 책임과는 멀다고 느껴서 TagService를 만들었는데 이렇게 서로 다른 Service끼리 의존을 하는 게 일반적인가요?
순환참조의 위험이나, 트랜잭션관리가 어려워질 수 있다는 단점이 있다고 들었는데 제 프로젝트에서 tag라는 도메인의 기능이 그렇게 복잡한 비즈니스 로직을 가질 것 같진 않아서 이렇게 구현했습니다.

2024-01-22 09:20 UTC, jzakka commented on src/main/java/com/stoury/service/FeedService.java
> +        Validator.of(writer.getId())
코드 줄이 더 길어지긴 했는데 오히려 일반 문장처럼 코드가 읽혀서 명확하고 좋다고 생각되는데 의견 부탁드립니다!

2024-01-24 14:40 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요!

2024-01-24 14:40 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Countries.java
> +    USA("United States of America"),
오 이게 뭐죠

2024-01-24 14:40 UTC, f-lab-moony commented on src/main/java/com/stoury/repository/FeedRepository.java
> +            select f
요건 약간 별거 아니긴한데 보통 쿼리는 예약어들을 대문자로, 오브젝트를 소문자로 써요

SELECT * FROM feed f ~~ 이런식으로요!

2024-01-24 14:40 UTC, f-lab-moony commented on src/main/java/com/stoury/service/FeedService.java
> +        Validator.of(writer.getId())
좋은 시도네요..!
근데 개인적으론 좀 더 읽기 힘들어진거같긴 합니다 ㅋㅋ 무슨 일을 하는지 직관적으로 보이는게 목표라면 그냥 메서드 분리를 통해서 이름을 부여해주는게 더 낫지 않나 싶네요..!

2024-01-24 14:40 UTC, f-lab-moony commented on src/main/java/com/stoury/service/FeedService.java
> +                .mapToObj(seq -> {
선언형의 장점은 어떻게 하냐보단 무엇을 하느냐에 초점을 맞추고 코드를 읽을 수 있어 가독성이 높아진다는데에 있는데요, 이런식으로 구현이 드러나게 표현하는 건 지양하는게 좋다고 생각합니다. 메서드로 분리해서 이 스코프에서는 무엇을 하는지만 볼 수 있도록 만들어보면 어떨까요 ?

2024-01-24 14:40 UTC, f-lab-moony commented on src/main/java/com/stoury/service/FeedService.java
> +    public Slice<FeedResponse> getFeedsOfMemberId(Long memberId, LocalDateTime orderThan) {
피드는 보통 클라이언트에서 스크롤 방식으로 구현이 될텐데, Pageable을 이용하는 방식에는 치명적인 단점이 있어요. More read 방식 페이징을 한번 찾아보시면 좋을 것 같아요!

2024-01-24 14:40 UTC, f-lab-moony commented on src/main/java/com/stoury/service/TagService.java
> +public class TagService {
요건 답변 드린대로! 전혀 이상한 방법이 아니니 개의치 말고 진행하시면 될 것 같습니다 ~

2024-01-24 14:40 UTC, f-lab-moony commented on src/main/java/com/stoury/utils/SupportedFileType.java
> +        return OTHER.equals(getFileType(file));
약간 사족인가 싶긴 한데, enum은 동일성 비교로 해도 괜찮습니다!

2024-01-24 14:40 UTC, f-lab-moony commented on src/test/java/com/stoury/service/FeedServiceIntegrationTest.java
> +public class FeedServiceIntegrationTest {
혹시 요거 통합테스트 해보시는 이유가 뭘까요 ?

2024-01-24 14:40 UTC, f-lab-moony commented on src/test/java/com/stoury/service/MemberServiceTest.java
> +        Member member3 = Member.builder().email("mem3@aaaa.com").encryptedPassword("pwdpwdpwdpwd").username("mexber3").build();
요건 그냥 제안이라 무시하셔도 되긴 하는데, 혹시 Spock 써보실 생각은 없으실까요 ㅋㅋ
이런거 fixture로 만들기가 용이해서 뭔가 되게 만족하실거같아서 제안해봅니다

2024-01-24 15:17 UTC, jzakka commented on src/main/java/com/stoury/domain/Countries.java
> +    USA("United States of America"),
#미국, #한국 이런 국가이름 태그는 미리 만들어둘려고 열거형을 정의해놨는데 당장은 쓸 일이 없을 것 같네요😅

2024-01-24 15:26 UTC, jzakka commented on src/main/java/com/stoury/service/FeedService.java
> +                .mapToObj(seq -> {
뭔가 내부 구현이 안드러나게 메서드로 캡슐화하기 애매한 느낌도 들긴합니다.
seq처럼 인덱스를 갖고 작업을 해야해서  이럴 땐 단순히 for 루프를 사용하는게 낫겠군요.
이 부분은 좀더 가독성있게 리팩토링 해보겠습니다!

2024-01-24 15:31 UTC, jzakka commented on src/test/java/com/stoury/service/FeedServiceIntegrationTest.java
> +public class FeedServiceIntegrationTest {
기존에 있던 테스트도 남겨두려고 했는데, 기존 테스트는 다른 의존성이 연관돼있어서 Integration이라고 이름을 붙였습니다. 아예 기존 테스트는 지우고 단위 모듈로 테스트할 수 있도록 바꾸는 게 나을까요?

2024-01-25 10:46 UTC, jzakka commented on src/main/java/com/stoury/service/FeedService.java
> +    public Slice<FeedResponse> getFeedsOfMemberId(Long memberId, LocalDateTime orderThan) {
일반 페이지네이션을 하게되면 pageSize*pageNum 만큼 오프셋을 전부 읽어와서 성능상의 이슈가 있는 걸로 알고 있습니다.
말씀하신 more read방식이 커서기반 페이지네이션을 말씀하시는 건가요?

그거라면, 제가 피드의 createdAt을 기준으로 페이지네이션을 할 수 있게 createdAt에 인덱스를 걸었습니다.
제가 예상하기로는 orderThan보다 오래된 createdAt을 가진 피드를 찾고 거기서부터 pageSize만큼 긁어오도록 동작을 하는 것입니다.

```sql
select
        f1_0.id,
        f1_0.created_at,
        f1_0.latitude,
        f1_0.longitude,
        f1_0.member_id,
        f1_0.text_content 
    from
        feed f1_0 
    where
        f1_0.member_id=? 
        and f1_0.created_at<? 
    order by
        f1_0.created_at desc 
    limit
        ?, ?
```
실제 쿼리는 이렇게 날아가는데 more-read방식이 제대로 적용된 것 같은데 맞나요?

2024-01-25 14:30 UTC, jzakka commented on src/test/java/com/stoury/service/MemberServiceTest.java
> +        Member member3 = Member.builder().email("mem3@aaaa.com").encryptedPassword("pwdpwdpwdpwd").username("mexber3").build();
Spock 추가해서 간단한 테스트 몇개 만들어봤습니다

given, when, then 절들을 필수적으로 지정하고, 파라미터화 테스트같은게 엄청 편하네요!

근데 스터빙이나 모킹 문법이 좀 난해하다고 느꼈습니다

예를들어 
```groovy
then:
memberRepository.save(_ as Member) >> Stub(Member)
1 * memberRepository.save(_ as Member)
```
위에건 안되고
```groovy
then:
1 * memberRepository.save(_ as Member) >> Stub(Member)
```
아래건 제대로 동작한다던가, 스터빙은 반드시 then절에 있어야 제대로 동작한다던지

제가 아직 익숙치 않아서 그런가봅니다🥲. 코드 리뷰어입장에서는 코드 작성자가 테스트 코드를 정해진 양식대로 작성하니까 오히려 가독성이 좋다고 느껴질 수도 있겠다고 생각이 드네요.

추가되는 기능이랑 기존 테스트를 조금씩 스파킹으로 옮겨보도록 하겠습니다

2024-01-25 14:31 UTC, f-lab-moony commented on src/main/java/com/stoury/service/FeedService.java
> +    public Slice<FeedResponse> getFeedsOfMemberId(Long memberId, LocalDateTime orderThan) {
엇 그러네요 Slice랑 Pageable을 보고 관성적으로 달았는데 ㅋㅋ
Pageable에 정렬이 정의되어서 more 방식으로 동작하는가보군요

그럼 Slice는 굳이 안써도 되지 않을까요 ?

추가로 .. Pageable을 이용한 페이징은 약간 직관적이지 못하다고 생각하는데, QueryDsl을 이용해서 구현해보는 건 어떻게 생각하시나요 ?

2024-01-25 14:31 UTC, f-lab-moony commented on src/test/java/com/stoury/service/FeedServiceIntegrationTest.java
> +public class FeedServiceIntegrationTest {
네 동일한 테스트같아서 굳이 남겨둘 필요 없어보입니다

2024-01-25 14:33 UTC, f-lab-moony approved these changes
고생 많으셨습니다!
요 PR은 머지 해둘게요 ~

2024-01-25 14:33 UTC, f-lab-moony commented on src/main/java/com/stoury/service/FeedService.java
> +        for (int i = 0; i < graphicContents.size(); i++) {
👍

2024-01-25 14:33 UTC, merged

2024-01-25 14:57 UTC, jzakka commented on src/main/java/com/stoury/service/FeedService.java
> +    public Slice<FeedResponse> getFeedsOfMemberId(Long memberId, LocalDateTime orderThan) {
List를 사용하는 것이 좋을 것 같네요!

쿼리 dsl을 경험삼아 시도해보고 싶기도 합니다. 근데 지금 같은 상황에서 쿼리 dsl을 사용했을 때 얻을 수 있는 장점을 잘 모르겠습니다.

보통 쿼리 dsl을 사용한다면 장점이
1. 문자열 sql대신 자바코드dsl로 작성하기 때문에 문법검사가 컴파일 타임에 이루어진다.
2. 동적쿼리를 만들기 쉽다.

인데, 1번의 경우 인텔리제이가 문자열 쿼리도 잘 체크해줘서 크게 장점이라고 와닿진 않고, 2번의 경우는 제가 아직 동적쿼리를 안써봐서 체감이 안됩니다.(어쩌면 무식하게 동적인 상황마다 정적으로 쿼리를 작성했을 것 같네요ㅎㅎ)

2024-01-26 16:48 UTC, f-lab-moony commented on src/main/java/com/stoury/service/FeedService.java
> +    public Slice<FeedResponse> getFeedsOfMemberId(Long memberId, LocalDateTime orderThan) {
1번은 컴파일 타임에 이루어진다는 장점이 사실 체크해주고 뭐를 떠나서 실수 할 여지를 줄여준다는게 더 크다고 생각해요, 아마 오타로 장애를 겪어보신다면 ( 당연히 베타테스트 하니까 그럴일 많이 없긴한데 ) 생각이 달라지실거라고 봅니다 ㅋㅋ

동적쿼리도 아마 필요할때가 오면 바로 느끼실거같은데, 제가 말씀드린 큰 이유는 Pageable을 사용하면서 페이징 처리에 대한걸 따로 읽어야하는 불편함때문이 크구요

개인적으로 쿼리dsl의 가장 큰 장점은 코드를 쿼리처럼 만들 수 있어서 테스트를 해보거나 할 때 괴리를 줄일 수 있는 점이라고 생각합니다!

2024-01-26 16:51 UTC, f-lab-moony commented on src/test/java/com/stoury/service/MemberServiceTest.java
> +        Member member3 = Member.builder().email("mem3@aaaa.com").encryptedPassword("pwdpwdpwdpwd").username("mexber3").build();
groovy 기반이라 상당히 자유도가 높아서 .. 한번 써보면 junit 따위로는 돌아가지 못하실겁니다 .. 저도 junit 안쓴지 몇년 된거같아요 ㅋㅋ

목킹은 전 사실 되게 직관적이라고 생각하긴 했는데요, 저번에 저희 팀원분도 저게 한꺼번에 있으니 given, then 정의할때 애매하다고 하시더라구요. 개인적으로 저는 verify가 필요한 부분은 then 뒤에 and로 이어서 작성해주고 verify가 필요 없으면 given절에 두는데, 이것도 순서가 헷갈린다고 하시는분들이 있긴 합니다 ㅋㅋ 전 별로 안헷갈려서 오히려 좋긴 한데 .. 취향인 것 같아요

좀 더 익숙해지시면 푹 빠지실거라 생각합니다! groovy 기반이라 얻을 수 있는 장점들도 많거든요, 예를들면 entity 테스트 시 id를 강제로 지정이 가능하다던지, 네임드 파라미터나 디폴트 밸류를 사용 가능하다던지 등등..!