[#11] 피드 좋아요 기능
f-lab-edu/Stoury pull request #12
Opened 2024-01-23 13:56 UTC by jzakka

### 기능
- 좋아요
- 좋아요 취소
-  한 피드에 사용자는 한 번만 좋아요 가능

### 변경
- Like도메인, 리포지토리, 서비스 생성
- feed는 필드로 좋아요수 likes를 가짐

2024-01-23 14:14 UTC, jzakka commented on src/main/java/com/stoury/domain/Feed.java
> +    @Formula("(SELECT COUNT(L.ID) FROM LIKES L WHERE L.FEED_ID = id)")
### 좋아요 수를 가상 필드로 둔 이유
서비스에서 `likeRepository`로 좋아요 수를 가져오고 응답에 넣어줘도 되지만 좋아요수를 피드 엔티티 자체에서 가지고 있는 편이 코드가 깔끔해진다고 생각했습니다. 
서비스에서 좋아요수를 가져오면, 엔티티, 서비스코드, 응답dto를 모두 수정해야합니다. 게다가 서비스코드를 수정하는 경우 `FeedResponse` 를 반환하는 메서드는 전부 수정해야 합니다. `FeedResponse.from(좋아요수)`이런식으로 응답dto를 생성하기 위한 값이 엔티티에 없어서 주입해줘야 하기때문입니다.
반면, 좋아요 수를 엔티티가 가지게 되면 엔티티, 응답 dto를 수정하면 된다고 생각하여 이런 식으로 구현했습니다.

### `@Formula`의 단점
- jpql을 사용하지 못합니다.
- 중간에 좋아요 수가 늘어나도 likes값이 자동으로 변경되지 않는다고 합니다. 엔티티 조회 시점에 쿼리가 날라가는 메커니즘이라고 합니다.

근데 대부분의 좋아요 시스템을 보면 사용자 뷰에서 좋아요 눌렀을 때 DB의 실시간 좋아요 수가 아닌, 사용자가 처음으로 게시글을 보게된 순간의 조회수를 보여주기 때문에 위의 두번째 단점이 크다고 생각되지는 않습니다. jpql이 적용안되는 점의 경우, 저 정도의 간단한 쿼리는 거의 대부분의 db에서 문법적으로 통용되기 때문에 괜찮지 않을까라는 생각입니다.

2024-01-24 14:47 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Feed.java
> +    @Formula("(SELECT COUNT(L.ID) FROM LIKES L WHERE L.FEED_ID = id)")
일단 .. 구현상의 이점이 비즈니스 구현의 이유가 되어선 안된다고 생각합니다.
비즈니스를 위해 개발자가 있는거지 개발자를 위해 비즈니스가 있는게 아니라서요. 필요하다면 말씀하신 수정내용들 전부 당연히 해야되는거라고 생각을 하구요

다음으로, 좋아요가 피드에 종속되는 도메인이 맞나? 하는 의문이 좀 드는데요. 가상 필드라는 개념 자체가, 같은 도메인에서 가지고 있는 컬럼만으로는 표현을 못하긴 하지만 별도의 컬럼을 추가하긴 애매한 상태에 쓰여야되지 않나 하는 생각이 좀 듭니다. 물론 그런 경우 그냥 가져와서 어플리케이션에서 조합하면 되는거라, 사실 `@Formula` 를 쓰는 것 자체에 조금 회의적이긴 하네요

왜 별도의 도메인인가는 뭐 .. 일단 도메인은 이미 분리 해두기도 하셨고, 피드를 볼 때, 좋아요는 실시간으로 반영이 되고 올라가는게 보일수도 있을거라 생각하는데 지금 구조라면 좋아요 수를 보기 위해 피드를 조회해야되는거 아닌가요 ? 약간 아예 별도의 api로 두고 클라이언트에서 호출 간격을 따로 가져가야되는 부분이 아닌가 하는 생각도 듭니다. 그렇게 되면 앞에 말씀하신 합치는 작업들도 필요가 없을거 같구요

2024-01-24 14:59 UTC, f-lab-moony requested changes
고생 많으셨습니다!
피드백 확인 부탁드려요 ~

2024-01-24 14:59 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Like.java
> +public class Like {
근데 이걸 보다보니 이거 이렇게 관리 가능한가 싶긴 하네요 ㅋㅋ 서비스가 커진다면 로우수가 엄청날거같은데요

2024-01-24 14:59 UTC, f-lab-moony commented on src/main/java/com/stoury/service/LikeService.java
> +    public void like(Member liker, Feed feed) {
제가 SNS 도메인을 안다뤄봐서 정확힌 모르겠지만, 제 생각에 좋아요 기능은 급격하게 높아지는 트래픽이 몰리는 구간이라고 생각 하거든요, 근데 여기서 write가 일어나면 서비스 전반적으로 굉장히 안좋은 영향을 끼치게 될 것 같아요.

그래서 의견인데, 그냥 캐시를 두고 좋아요 수를 카운트로 관리를 하면서 주기적으로 DB에 업데이트를 하는 스케줄러를 두는 식으로 관리하는 건 어떨까요 ?

2024-01-25 15:59 UTC, jzakka commented on src/main/java/com/stoury/domain/Like.java
> +public class Like {
한 사용자가 한 게시글을 중복추천하지 못하게 하려면 이 방법밖에 없다고 생각돼서요.

아니면 기능 요구사항을 바꿔서 
'한 사용자는 하루에 한번만 추천 가능하다'로 바꾸는 건 어떨까요
이렇게 하면 세션에 추천 정보를 저장하고 추천수는 단순 int로 feed의 컬럼으로 만들 수 있다고 생각됩니다.

근데 요구사항을 바꾸는 건 좀 찜찜하긴 하네요😅
구글링 해봤는데 다 투표 테이블을 만들어서 사용자id와 게시글id에 유니크를 건 거 밖에 없어서...

2024-01-26 04:29 UTC, jzakka commented on src/main/java/com/stoury/domain/Feed.java
> +    @Formula("(SELECT COUNT(L.ID) FROM LIKES L WHERE L.FEED_ID = id)")
좋아요라는 도메인이 피드에 종속적인 도메인으로 보긴 어렵기 때문에 `@Formula`를 사용하기 적절하지 않다라는 말씀이시군요.

`좋아요 수 실시간 조회가 가능할 수 있도록 별도 API로 빼보는 것을 생각할 수 있음 => 그러려면 LikeService에서 count를 호출해 오는게 더 낫다.`

좋아요 수를 별도 API로 분리하면 피드 정보를 볼 때 네트워크를 한 번 더 타게 될 것같은데 이런게 이슈를 일으킬 수도 있나요?
보통 어떤 게시글(혹은 피드)의 좋아요수만 따로 조회하지 않고 피드를 단일 조회, 혹은 여러 피드리스트를 보면 좋아요수가 같이 나오는데 만약 피드리스트로 보면 
`피드 리스트 요청 => 응답받은 피드들에 대한 좋아요 요청` 이런 식으로 흘러갈 것 같습니다.

그럼 `피드 리스트 요청 1 + 피드에 대한 좋아요 N`개의 요청이 나가게 되는 게 아닌지 생각이 듭니다.

2024-01-26 05:27 UTC, jzakka commented on src/main/java/com/stoury/service/LikeService.java
> +    public void like(Member liker, Feed feed) {
좋아요수를 카운트로만 관리하면 중복 좋아요 처리를 하기가 힘들 것 같습니다. 제 생각엔 캐싱을 도입해도 

feed_id마다 좋아요한 사람id를 set으로 저장해야한다고 생각합니다. 물론 전체 피드가 아니고 캐시에 없는 피드에 대한 추천이 들어오면 그때 feed_id : [member_id1, member_id2, ...] 이런식으로요.

제가 생각한 캐시 시나리오는

1. 사용자가 like 요청
2. 중복 like인지 체크
a. 캐시에 이미 데이터 있니? `yes` -> block, `no` -> 2-b
b. db에 이미 데이터 있니? `yes` -> block, `no` -> 3
3. 캐시에 데이터 저장
4. 스케줄러가 주기적으로 캐시를 DB로 업데이트

이렇게 하면 쓰기는 사용자에 의한 쓰기는 항상 캐시로 발생하고 DB업데이트는 스케줄러에 의해서만 발생하게 되지 않을까요.

2024-01-26 16:35 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Feed.java
> +    @Formula("(SELECT COUNT(L.ID) FROM LIKES L WHERE L.FEED_ID = id)")
네 아예 api까지 분리를 하면 말씀하신대로 동작을 하게 될 것 같아요
이건 클라이언트가 어떻게 구현되느냐에 따라 다르긴 한데, 보통 피드 보여주는 걸 생각하면, 최초 로딩시에는 좋아요 수가 같이 내려오는게 나을 것 같기도 하네요!
하지만 좋아요는 피드와 달리 계속 갱신이 일어날 수 있는 부분이라, 따로 조회하는 api가 별도로 있는건 맞을 것 같아요
전체 조회에서도 주고 별도로 호출도 가능한 구조면 좋지 않을까 합니다!

`@Formual` 관련해서는 사용하는게 큰 문제는 없고, 구현 방식의 하나라 그냥 제가 익숙치 않은 방식이라 거부감이 드는거 같기도 한데요. 제 생각에 썼을때의 단점은 아래와 같습니다

- 엔티티의 성격과 다른 도메인의 정보를 가져오는 쿼리가 클래스에 침투한다
- 해당 필드는 보통의 엔티티를 다루는것과 다를거라 사용 시 신경을 써야 한다 ( 가상필드니 업데이트 등은 안될거니까요..! )
- 서브쿼리로 수행 될거 같아서 성능 저하가 없는지 주의가 필요하다 ( 데이터 많아지면 무조건 느려질거같긴 한데 .. )

요런 불편한 생각들이 자꾸 들어서 ㅋㅋ 그냥 도메인에 맞게 역할을 주는게 좋지 않나 생각합니다

2024-01-26 16:38 UTC, f-lab-moony commented on src/main/java/com/stoury/service/LikeService.java
> +    public void like(Member liker, Feed feed) {
오 안그래도 저 위에 코멘트만 알림으로 보고 요 방법 제시하려고 했었는데 저와 의견이 일치하셨네요 ㅎㅎ
추가로 사용자 요청 전에, 어플리케이션 구동 시 캐시 초기화 과정이 있으면 좋을 것 같습니다!
이것도 데이터가 많아지면 메모리캐시로는 감당이 안될거 + 클러스터링 구성할 경우 동기화를 위해서 외부 캐시 (feat. 레디스)로 빼는걸 고려해보면 좋을 것 같긴 한데, 일단 구현은 저도 말씀하신대로 하는걸 동의합니다!

중요한건 좋아요 요청 당 1건의 insert가 일어나는걸 막는거라고 생각해요

2024-01-26 16:43 UTC, f-lab-moony approved these changes
고생 많으셨습니다!
PR 머지해둘게요!

2024-01-26 16:43 UTC, f-lab-moony commented on src/test/groovy/com/stoury/LikeServiceTest.groovy
> +    def memberRepository = Mock(MemberRepository)
요거 def 말고 클래스 타입으로 쓰면 뒤에 `Mock()` 요렇게만 써도 될거에요!
꼭 바꾸라는건 아니고 맘에 드는거 쓰시라고 적어봤습니다 ㅎㅎ

2024-01-26 16:43 UTC, f-lab-moony commented on src/test/groovy/com/stoury/LikeServiceTest.groovy
> +        setup:
setup이 있네요 ? 보통 given을 써서 저런게 있는지도 몰랐군요 ㅋㅋ

2024-01-26 16:43 UTC, f-lab-moony commented on src/test/groovy/com/stoury/LikeServiceTest.groovy
> +        1 * likeRepository.save(_ as Like)
이 save 자체가 검증 목표라면, 넘겨받은 파라미터를 검사해보는것도 좋은 방법이라고 생각해요

```
1 * likeRepository.save(_ as Like) >> { args ->
  def like = args[0] as Like

 like.id == 1L
}
```

요런느낌 ?

2024-01-26 16:43 UTC, merged

2024-01-28 03:32 UTC, jzakka commented on src/main/java/com/stoury/service/LikeService.java
> +    public void like(Member liker, Feed feed) {
저도 레디스가 이런 키-값 기반 자료구조를 다양하게 제공해줘서 레디스가 좋다고 생각합니다!

2024-01-28 03:34 UTC, jzakka commented on src/test/groovy/com/stoury/LikeServiceTest.groovy
> +        setup:
전 given에는 테스트 입력이 정의되고, setup에는 스터빙이나 모킹이 적절하다고 생각해서 이렇게 했는데, 보통 given에도 스터빙을 하나요?

2024-01-28 03:40 UTC, jzakka commented on src/test/groovy/com/stoury/LikeServiceTest.groovy
> +        1 * likeRepository.save(_ as Like)
`like.id==1L`이 넘겨받은 like 객체의 id가 1L인지 검증하는 코드인가요?
제 생각에는 save를 할 때 들어가는 엔티티는 아직 영속화 되지 않아서 id가 없을 것으로 예상됩니다.

2024-01-28 04:19 UTC, f-lab-moony commented on src/test/groovy/com/stoury/LikeServiceTest.groovy
> +        setup:
보통이라고 해야하나 .. 원래 테스트에서 사용하는 페이즈가 given-when-then 밖에 없어서 setup이라는 페이즈는 사실 beforEach같은 픽스처 메서드 말고는 써본적이 없네요

원래 메서드 모킹도 given에서 하고는 있습니다

2024-01-28 04:19 UTC, f-lab-moony commented on src/test/groovy/com/stoury/LikeServiceTest.groovy
> +        1 * likeRepository.save(_ as Like)
네 저건 예시고 저런식으로 `전달받은 파라미터를 검증하는 방법`에 대해 말씀드려봤어요 ~