[#13] 댓글 기능
f-lab-edu/Stoury pull request #14
Opened 2024-01-26 09:37 UTC by jzakka

### 댓글 기능
- 피드에 댓글 달기
- 댓글에 대댓글 달기, 대대댓글 불가
- 피드의 댓글 조회
- 댓글의 대댓글 조회

### 변경
- 댓글 서비스
  - 댓글 생성
  - 대댓글 생성: 대댓글을 달려는 댓글도 대댓글이라면 예외 던짐
  - 댓글 조회
  - 대댓글 조화: 조회대상 댓글이 대댓글이면 예외 던짐
  - 댓글 삭제: 댓글 삭제되도 조회 가능, 내용이 '삭제된 댓글'로 표시
- Validator 클래스
  - 서비스에 검증로직이 들어가서 단위테스트가 불편
  - 그리고 다른 서비스에도 비슷한 검증로직이 중복
  - 클래스로 만들어서 컴포넌트화

2024-01-26 17:15 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 남겨뒀는데 확인 부탁드려요!

2024-01-26 17:15 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Comment.java
> +    List<Comment> nestedComments = new ArrayList<>();
접근지정자가 없어요!

2024-01-26 17:15 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Comment.java
> +    List<Comment> nestedComments = new ArrayList<>();
아래가 parent라서 얘네는 childComments로 하는게 어떨까요 ?

2024-01-26 17:15 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Like.java
> +@Table(name = "LIKES", uniqueConstraints = @UniqueConstraint(name = "LIKES_UNIQUE_CONSTRAINTS",
지금은 요런게 생기거나 변경되면 JPA가 자동으로 처리해주고 있을 것 같은데, 혹시 flyway를 도입해보는건 어떨까요 ? db 형상관리 툴인데 개발시에는 조금 불편한 점이 있을 수 있지만 추후 운영에서는 JPA의 ddl 기능을 쓰지 않을거라서 한번 사용해보시면 좋을 것 같습니다!

2024-01-26 17:15 UTC, f-lab-moony commented on src/main/java/com/stoury/service/CommentService.java
> +        Comment comment = new Comment(member, feed,
리턴값이 있어도 유효성검사는 따로 빼주는게 좋을 것 같아요~

2024-01-26 17:15 UTC, f-lab-moony commented on src/main/java/com/stoury/service/CommentService.java
> +        Comment savedComment = commentRepository.save(comment);
요거 따로 쓰는데가 없는데 요건 from 안에 인라인으로 넣어도 되지 않을까요 ?

2024-01-26 17:15 UTC, f-lab-moony commented on src/main/java/com/stoury/service/CommentService.java
> +    public void deleteComment(Comment comment) {
엇 이제보니 다른것도 비슷하긴 한데, 요거 어떻게 쓰려고 Comment가 파라미터로 넘어오는걸까요 ?
제가 생각한건 CommentController가 있을거고, 거기서 CommentService를 주입받을거라 여기로는 Request들, delete니까 commentId 정도가 넘어와야 될 것 같은데 혹시 다른 방법 생각하시는걸까요 ~?

2024-01-27 00:25 UTC, jzakka commented on src/main/java/com/stoury/service/CommentService.java
> +        Comment comment = new Comment(member, feed,
따로 빼준다는 게 함수로 추출하는 걸 말씀하시는 걸까요?

'리턴값이 있어도' 는 어떤 걸 말씀하시는 지 잘 모르겠습니다

2024-01-27 00:27 UTC, jzakka commented on src/main/java/com/stoury/service/CommentService.java
> +    public void deleteComment(Comment comment) {
아뇨, 지금보니 잘못 작성했네요..
다 id로 수정하겠습니다

2024-01-27 12:11 UTC, f-lab-moony commented on src/main/java/com/stoury/service/CommentService.java
> +        Comment comment = new Comment(member, feed,
아뇨 위에서 유효성검사 할때 같이 하고 여긴 그냥 매개변수 넘어온거 쓰는게 나을 것 같다는 말이었어요 ~
리턴값이 있어서 지금처럼도 넘길 수는 있는데 생성하는데 유효성검사 구문이 같이 섞여있어서요!

2024-01-28 03:18 UTC, jzakka commented on src/main/java/com/stoury/service/CommentService.java
> +        Comment comment = new Comment(member, feed,
일단 feed나 member가 넘어오는걸 feedId랑 memberId가 넘어오도록 수정했습니다. 그래서 엔티티를 가져올 때 유효성검사가 같이 되도록 했습니다. 

'위에서 유효성검사'라는 말씀이 서비스로 데이터가 넘어오기 전을 말씀하시는 건가요??

2024-01-28 03:19 UTC, jzakka commented on src/main/java/com/stoury/domain/Like.java
> +@Table(name = "LIKES", uniqueConstraints = @UniqueConstraint(name = "LIKES_UNIQUE_CONSTRAINTS",
어떤기술인지 알아보고 적용해보겠습니다!

2024-01-29 16:00 UTC, f-lab-moony commented on src/main/java/com/stoury/service/CommentService.java
> +        Comment comment = new Comment(member, feed,
아뇨아뇨 validator에서 검증하는거랑 같이 유효성검사하는 로직은 뭉쳐놓는게 좋을 것 같다는 얘기였어요

2024-01-29 16:00 UTC, f-lab-moony approved these changes
고생 많으셨습니다!
바로 머지 하도록 할게요 ~

2024-01-29 16:00 UTC, merged