[#1] 회원가입 기능
f-lab-edu/Stoury pull request #2
Opened 2024-01-11 02:22 UTC by jzakka

- BCrypt로 비밀번호 암호화
- 서비스에서는 사용자정보를 dto로 받아오고 dto를 반환
- model mapper 로 엔티티와 dto 변환

### 테스트
- 일반적인 성공 테스트
- 필수 기입 항목(이메일, 사용자이름, 비밀번호) 누락시 실패 테스트

기입 정보 누락 시 예외가 repository에서 예외를 그대로 던지는데 서비스에서 이걸 어떤 예외로 변환하는 게 좋을지 잘 모르겠네요.

2024-01-11 15:53 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백을 좀 남겨 두었는데, 확인 후 다시 푸시 해 주세요 ~

2024-01-11 15:53 UTC, f-lab-moony commented on src/main/java/com/stoury/aop/ServiceAspect.java
> +public class ServiceAspect {
예외처리를 위해 AOP 사용하신걸로 보이네요 ~
서비스 레이어에서 유효성검사를 통해 커스텀 예외를 던지도록 설계하고 `@ExceptionHandler` 를 이용해보시면 좋을 것 같아요 ~

2024-01-11 15:53 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Member.java
> +@AllArgsConstructor
lombok에서 가급적 사용을 하지 말라는 어노테이션들이 있는데 어떤 것들이 있는지와, 왜 그런지 한번 찾아보면 좋을 것 같아요 ~

2024-01-11 15:53 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Member.java
> +@Builder
`@Builder` 도 클래스에 선언하기보다 생성자에 선언하는걸 권장하는데, 이것도 왜 그런지 찾아보면 좋을 것 같습니다 ~

2024-01-11 15:53 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Member.java
> +    @Column(nullable = false, length = 60)
기본적으로 필드명을 기반으로 컬럼명이 생성이 되긴 하지만, `@Column` 이나 `@Table`엔 이름을 정해주는 게 좋아요. 명시적으로 보이는 효과도 있고 혹시 변수명의 변경이 필요할 때 db에 관계 없이 바꿀수도 있고, 예상치 못한 이름으로 만들어지는 걸 방지할 수 있어요

2024-01-11 15:53 UTC, f-lab-moony commented on src/main/java/com/stoury/service/MemberService.java
> +public interface MemberService {
서비스를 인터페이스로 빼는 이유가 있을까요 ?

2024-01-11 15:53 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        Member member = modelMapper.map(memberDto, Member.class);
DTO와 Entity간에 너무 강한 규약이 생기는거 아닐까요 ?

2024-01-11 15:53 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        member.setEncryptedPassword(encryptedPassword);
modelMapper를 사용하기 위해 불필요한 setter가 사용되는 것 같은데 어떻게 생각하시나요 ?

2024-01-11 15:53 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        return modelMapper.map(member, MemberDto.class);
위에 DTO -> Entity 도 그렇지만, 여기서도 눈에 보이지 않는 작업들을 염두에 두고 만들어지는 기분이 들어요.
추가로, 유저 정보의 응답에서 password를 가지고 있어야 할 필요가 있을까요 ?

2024-01-11 15:53 UTC, f-lab-moony commented on src/main/java/com/stoury/dto/MemberDto.java
> +public class MemberDto {
개인적으로 클래스명에 Dto 라는 prefix가 붙는 걸 별로 안좋아하는데, Request / Response 등과 같이 명명해도 충분히 DTO라는걸 인지할 수 있고, 컬렉션에 넣게됐을 때 Dtos 처럼 이상한 단어가 나오는게 별로여서 그렇습니다

2024-01-11 15:53 UTC, f-lab-moony commented on src/test/java/com/stoury/service/MemberServiceTest.java
> +        memberDto = MemberDto.builder()
테스트의 given 절에 해당하는 데이터들은 중복이 있더라도 각 테스트에서 직접 선언하는게 가독성을 높일 수 있어요
중복을 최소화 하는 방법으로 `Fixture` 에 대해서 찾아보시면 좋을 것 같습니다 ~

2024-01-11 15:53 UTC, f-lab-moony commented on src/test/java/com/stoury/service/MemberServiceTest.java
> +        assertFailByException(noEmail);
이런식의 반복되는 테스트는 `@ParameterizedTest` 로 처리해보면 좋을 것 같아요 ~

2024-01-11 15:53 UTC, f-lab-moony commented on src/test/java/com/stoury/service/MemberServiceTest.java
> +                .isInstanceOf(IllegalStateException.class);
repository의 save에서 던지는 예외를 잡으시는 것 같은데, save가 불리기 전에, 서비스가 자체적으로 유효성검사를 통해 의미 있는 메세지를 담은 예외를 던져주면 좋을 것 같아요 ~ `Objects.requireNonNull()` 을 활용해보면 어떨까요 ?

2024-01-12 03:46 UTC, jzakka commented on src/main/java/com/stoury/service/MemberService.java
> +public interface MemberService {
의존관계는 항상 인터페이스로 연결하는 것이 좋다고 들어서 이렇게 하긴 했는데 
프로젝트에서 다른 멤버서비스가 필요할 것 같진 않긴 합니다.

2024-01-12 03:50 UTC, jzakka commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        Member member = modelMapper.map(memberDto, Member.class);
강한 규약이라는 게, dto와 엔티티가 강한 결합도를 말씀하시는 걸까요?

그런거라면 엔티티 필드가 변하면 dto도 수정을 해야하는 문제가 있을 수 있겠군요.
조금더 고민해보겠습니다!

2024-01-12 03:51 UTC, jzakka commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        member.setEncryptedPassword(encryptedPassword);
저도 그 부분이 찜찜했는데, modelMapper말고 다른 방법을 찾아 보겠습니다

2024-01-12 03:56 UTC, jzakka commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        return modelMapper.map(member, MemberDto.class);
회원 생성 요청을 위한 dto랑 회원 정보를 반환하는 dto를 구분하면 응답에서 password를 제외시킬 수 있을 것 같습니다.

눈에 보이지 않는 작업이란 건 어떤 것인지 잘 모르겠습니다.

2024-01-12 05:45 UTC, jzakka commented on src/test/java/com/stoury/service/MemberServiceTest.java
> +                .isInstanceOf(IllegalStateException.class);
Objects.requireNonNull()을 이용해서 엔티티 생성 전에 피드 값을 검증하면

```java
String encryptedPassword = passwordEncoder.encode(Objects.requireNonNull(requestMember.password())); // 여기에 null 검증

        Member member = Member.builder()
                .email(Objects.requireNonNull(requestMember.email())) // 여기도 null 검증
                .username(Objects.requireNonNull(requestMember.username())) // 또 null 검증
                .encryptedPassword(encryptedPassword)
                .introduction(requestMember.introduction())
                .build();
```

이런 식으로 필드마다 requireNonNull이 붙게 되는데 차라리 controller에서 넘어오는 RequestMember(구 dto)가 항상 완전무결한 데이터임을 기대하고, 검증은 controller에서 하는 것은 어떤가요?

스프링 validator로 컨트롤러에서 입력받을 때부터 필드에 대한 검증을 하고 bindingResult로 대응해주면 서비스에서는 더 코드가 깔끔해질 것 같아서요

***

혹시 리포지토리에서 발생할지도 모르는 에러들은 aop로 서비스가 MemberCreateException(runtime ex임)를 던지도록 했습니다.

2024-01-13 14:41 UTC, f-lab-moony commented on src/main/java/com/stoury/service/MemberService.java
> +public interface MemberService {
같은 형태의 다른 구현체가 필요한 경우는 당연히 인터페이스가 좋겠지만, 항상 인터페이스가 좋다는데엔 동의하기가 어렵네요

확장에 유연한 구조는 물론 중요하긴 한데, 확장이 필요한가가 당연히 먼저 고민이 되어야 한다고 생각합니다.
그래서 추상화는 처음부터 설계하기보단 필요한 시점에 위로 올리는 느낌으로 바라봐야 한다고 생각해요

무분별한 인터페이스 사용은 오히려 생산성을 저하시키고 패키지 관리를 어렵게 만들면서 코드 가독성을 떨어뜨릴수가 있습니다

2024-01-13 14:42 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        return modelMapper.map(member, MemberDto.class);
memberDto의 password와 Member 엔티티의 encryptedPassword가 이름으로 매칭이 안돼서 아마 Response로 맵핑할 때 정보가 빠져있을 것 같아서 암호가 외부로 노출이 안되는 작업을 노리신거 아닌가 싶었는데 아닌가보군요 ?

2024-01-13 14:46 UTC, jzakka commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        return modelMapper.map(member, MemberDto.class);
네 맞습니다 엔티티에서는 encrypted...이고 dto에서는 password라서 맵핑이 안되니까 응답정보에 password가 안 들어갈 것을 생각했습니다.

근데 읽는 사람 입장에서 응답정보에 패스워드가 들어간 것처럼 보일 수도 있겠다 싶어서 이부분은 요청과 응답 dto를 분리하여 수정했습니다.

2024-01-13 14:56 UTC, f-lab-moony commented on src/test/java/com/stoury/service/MemberServiceTest.java
> +                .isInstanceOf(IllegalStateException.class);
말씀하신대로 필드마다 붙는걸 제안드린게 맞고 위치는 메서드 진입지점에서 하는걸 생각했어요 ~

서비스 입장에서 완전무결한 데이터임을 기대하는건 옳지 못한 방법입니다. 서비스가 더 도메인에 가깝게 닿아있는 레이어이기 때문에 어떤 데이터가 들어오더라도 서비스에 영향이 없도록 책임을 가져가는게 맞습니다.

validator로 유효성 검사를 하는 걸 컨트롤러에서 하는걸로 제안을 주신 것 같은데, 정확히는 컨트롤러에서 하는 작업은 아니라 맞게 이해했는지 약간 헷갈리네요 ..! 아무튼, validator를 이용하는것도 괜찮긴 합니다만, 전 개인적으로 가능한 건 각 레이어에서 다 검증을 해야 된다고 생각합니다.

예를 들어, 서비스에 유효성검사가 없이, Request에 어노테이션으로 검증을 진행 했을 때 이 서비스를 이용하는 다른 컨트롤러 혹은 다른 Request가 추가 되었는데, 그 유효성 검사가 빠지면 서비스는 오작동 하고 새로 작업한 사람에게 책임을 넘기는게 맞을까요 ? 아니면 빼먹었더라도 서비스엔 지장이 없게 예외를 던져 끊어내고 조기에 인지하여 수정될 수 있도록 시스템적으로 보완을 하는게 맞을까요 ?

말씀하신대로 코드가 깔끔해 보일 수는 있겠지만, 최소한 필요한 부분은 있어야 한다고 생각합니다. 저희가 방청소를 하는데 부엌을 깔끔하게 한다고 냉장고랑 씽크대를 버리지는 않는 것처럼요..!

추가로, validator를 사용하는 건 괜찮은데, 저는 개인적으로 별로 선호하진 않습니다. `@NotNull` 같은 어노테이션은 편하게 사용할 수 있지만, 어노테이션만으로 모든 종류의 유효성검사가 가능한게 아니기때문에 결국 유효성검사하는 부분이 파편화가 돼서 한 기능이 제대로 동작하기 위한 조건을 보려면 여기저기 다 살펴봐야 하는 경우가 생겨서요. 하지만 뭐 쓰신다면 말리지는 않지만 그게 서비스에 유효성검사를 빼도 되는 이유가 되지는 못한다고 생각합니다 :)

> 혹시 리포지토리에서 발생할지도 모르는 에러

는 어떤걸 상정하고 계신건지 모르겠네요, 리파지토리에서 발생할 것 같은 예외가 있다면 서비스에서 유효성검사를 하고 미리 막는게 맞다고 생각하고 정말 예기치 못한 예외라면 위에 말씀드리것처럼 ExceptionHandler로 잡을 수 있을텐데 AOP로 처리하는 이유가 잘 이해가 안되네요..!

2024-01-13 15:16 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요!

2024-01-13 15:16 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        Member member = Member.builder()
요 작업을 Request에 toEntity 정도로 넘겨보면 어떨까요 ?

2024-01-13 15:16 UTC, f-lab-moony commented on src/main/java/com/stoury/dto/RequestMember.java
> +public record RequestMember(String email, String password, String username, String introduction) {
보통 Request나 Service, Controller 이런 역할을 지칭하는 단어는 도메인 뒤에 들어가요..!

2024-01-13 15:16 UTC, f-lab-moony commented on src/test/java/com/stoury/service/MemberServiceTest.java
> +        assertFailByException(requestMember);
이 테스트 상화님이 아니라, 상화님이 프로젝트를 하는데 오늘 막 팀에 들어온 신입이 봤다고 가정했을 때, 어떤 테스트를 하는건지 알 수 있을까요?

서비스 내에서는 명시적으로 예외를 던지는 부분이 없으니 왜 예외가 나는지부터 고민할거고, 그게 왜 MemberCreateException인지 고민하고 AOP 선언된 부분까지 찾고 다 알아야 이해할 수 있는 테스트로 보여요

2024-01-13 15:16 UTC, f-lab-moony commented on src/test/java/com/stoury/service/MemberServiceTest.java
> +                Arguments.of(RequestMember.builder().password("pppppwwwwwaaaa").username("chung").build()),
요거 빌더를 써서 더 그런거 같은데, 어떤걸 null로 세팅하려는지 잘 와닿지가 않네요
email, username, password를 각각 넘겨주도록 하고 RequestMember로 만드는 건 테스트에서 하는게 어떨까요 ?

2024-01-13 15:16 UTC, f-lab-moony commented on src/test/java/com/stoury/service/MemberServiceTest.java
> +        ResponseMember createMember = memberService.createMember(requestMember);
여기서 쓰는 requestMember가 지금은 메서드가 몇개 안돼서 괜찮지만, 나중에 조건이 늘어나고 메서드가 많아졌을 때, 어떤 값으로 세팅되었는지 일일이 다 알 수 있을까요? 매번 위에 setup까지 올라와서 보고 무슨값인지 기억하고 내려가서 검증부분 보고 .. 이러면서 왔다갔다 하게 될 것 같아요

2024-01-13 15:17 UTC, f-lab-moony commented
요거 혹시 다른거 푸시하신게 있는걸까요 ? 머지가 막혀있네요 ~ 작업 추가하신거라면 충돌 해결 부탁드려요!

2024-01-13 15:21 UTC, f-lab-moony commented
갈린거라곤 PR봇 추가밖에 안보이는데 .. 그냥 요 브랜치에 main 머지나 리베이스 한번 해주시면 될 것 같네요..!

2024-01-13 15:51 UTC, jzakka commented on src/test/java/com/stoury/service/MemberServiceTest.java
> +                .isInstanceOf(IllegalStateException.class);
서비스의 재사용성을 생각해보면 검증을 서비스가 하는 것이 맞겠군요!

리포지토리에서 발생하는 에러는 DataIntegrityViolationException 같이 데이터베이스에 관한 에러를 말씀드린 것입니다. 

ExceptionHandler는 제가 제대로 알고 있는 건지는 모르겠는데 예외를 컨트롤러에서 잡는 걸로 알고 있습니다.

그러면 DataIntegrityViolationException이 컨트롤러까지 올라가서 그때 비즈니스에 관한 예외로 변환되는데, 저는 서비스가 DataIntegrityViolationException을 그대로 던지기 보단 서비스레이어에서 비즈니스 예외를 변환시키고 싶어서 aop를 사용했습니다.

2024-01-13 15:58 UTC, jzakka commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        Member member = Member.builder()
RequestMember 에서 member를 생성하는 것을 말씀하시는 걸까요?

그거라면 저도 그 생각을 해봤는데 
그러면 RequestMember가 인코딩된 패스워드를 가져야 하는데 RequestMember 필드가 final이라서 좀 애매합니다.
그렇다고 dto에서 password만 setter로 인코딩된 패스워드를 주입하자니 그것도 이상해서 이렇게 짰습니다...

2024-01-13 17:20 UTC, jzakka commented on src/test/java/com/stoury/service/MemberServiceTest.java
> +        assertFailByException(requestMember);
제가 테스트를 고려하지 않고 aop를 생각없이 도입한 것 같네요...

단순히 try catch로 DataAccess예외를 커스텀 예외로 던지는 게 나을까요?
아님 ExceptionHandler가 이를 처리하도록 하는 게 좋을까요

제 생각엔 DataAccess예외를 서비스 레이어에서 커스텀 예외로 변환해주는 게 맞다고 생각하기는 합니다.

2024-01-14 14:27 UTC, f-lab-moony commented on src/test/java/com/stoury/service/MemberServiceTest.java
> +                .isInstanceOf(IllegalStateException.class);
네 그런 예외들은 전부 설계 혹은 입력값이 잘못되어서 발생하는 예외들인데, 그게 발생하는걸 상정하고 개발하신다는게 무슨 뜻인지 이해가 안가서요 ~ 의도하고 이후 작업을 커트한게 아니라 잘못된 동작인거니까요..!

ExceptionHandler는 컨트롤러보다 더 바깥으로 보시는게 맞을 것 같긴 한데, 어쨌든 말씀하신대로 서비스에서 발생 된 예외가 더 앞단에서 핸들링되는 건 맞습니다. 예외를 변환하려는 의도는 이해를 했습니다. 하지만 여전히 이게 AOP를 쓰는 이유로는 납득이 안가네요..!

일단 DB 작업에서 발생하는 예외는, 트랜잭션 종료 후 발생하는거라 애초에 서비스에서 핸들링이 가능한 영역이 아니라서 발생한다면 안하도록 앞에서 처리하게 수정을 하는게 맞다고 생각하구요. AOP로 예외를 핸들링하는 것 자체가 가독성이 현저하게 떨어진다고 생각합니다. 지금 타겟도 메서드 하나를 짚어서 보고 있어서 AOP로 처리할만한 부분이 맞나 싶은것도 있구요. 그리고 예외를 잡아서 컨버팅만 하고 있어서, 적절한 메세지를 넣기도 힘들어보입니다.

사실 AOP로 예외핸들링을 시도하는걸 처음 봐서 더 부정적으로 보이는 걸 수도 있는데요, 상화님이 생각하시는 AOP로 예외핸들링을 했을 때의 또 다른 장점이 있다면 설명 한번 해주시면 좋을 것 같아요 :)

2024-01-14 14:28 UTC, f-lab-moony commented on src/test/java/com/stoury/service/MemberServiceTest.java
> +        assertFailByException(requestMember);
오 위에도 남겼지만, repository에서 발생할 수 있는 예외는 발생 안하도록 조기에 처리하는게 맞다고 생각해요
db 작업에 관한 예외는 애초에 서비스 레이어에서 발생하는게 아니라 핸들링하기 쉽지 않을거에요..!

2024-01-14 14:33 UTC, f-lab-moony approved these changes
고생 많으셨습니다!
머지를 하고싶은데 충돌이 나고있네요 충돌 해결 후 셀프머지 부탁드려요 !

2024-01-14 14:33 UTC, f-lab-moony commented on src/main/resources/application.yml
> +member:
요거 좀 흥미로운데, 저는 상수로 쓰는거에 비해 설정파일로 관리하는게 어떤 이득이 있는지 생각이 안나는데, 혹시 특별한 이유가 있으신가요 ?

2024-01-14 14:33 UTC, merged

2024-01-14 14:33 UTC, f-lab-moony commented
음? 코멘트 달고나니까 블락이 풀려서 그냥 제가 머지 했어요 ㅋㅋ

2024-01-15 03:21 UTC, jzakka commented on src/test/java/com/stoury/service/MemberServiceTest.java
> +                .isInstanceOf(IllegalStateException.class);
aop로 이메일 중복 예외를 처리하려 했는데 확실히 배보다 배꼽이 더 큰 것 같기도 하고 코드를 더 난해하게 만들 수도 있다고 생각이 드네요.

서비스에서 데이터를 넣기 전에 미리 중복 체크를 하는 건 어떤가요? 쿼리가 한 번 더 날아가긴 하는데 이정도가 실무에서 큰 영향을 끼칠까요?

2024-01-15 13:38 UTC, f-lab-moony commented on src/test/java/com/stoury/service/MemberServiceTest.java
> +                .isInstanceOf(IllegalStateException.class);
중복처리는 보통 말씀하신대로 유효성검사를 합니다!