[#20] 로그인 기능
f-lab-edu/Stoury pull request #21
Opened 2024-01-29 07:59 UTC by jzakka

### 기능
- POST`/login` 으로 로그인
- POST`/members`로 회원가입
- 토큰 만료시간 1시간
- 토큰 바디에 사용자 이메일
- `Authorization: Bearer {token}`으로 반환
### 변경
- JWT토큰 패키지 추가
- MemberService테스트 그루비 단위테스트로 옮김
- 로그인을 위한 시큐리티 필터체인 구성, MemberService가 UserDetailService의 역할을 하게 함

2024-01-29 16:37 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요!

2024-01-29 16:37 UTC, f-lab-moony commented on src/main/java/com/stoury/config/SecurityConfig.java
> +    public class AuthenticationFilter extends UsernamePasswordAuthenticationFilter {
요거 그냥 빈으로 만들어도 되지 않을까요 ?

2024-01-29 16:37 UTC, f-lab-moony commented on src/main/java/com/stoury/utils/JwtUtils.java
> +public class JwtUtils {
혹시 JWT를 선택한 이유가 뭘까요 ?
세션 방식와 JWT의 차이는 어떤게 있을까요 ?

2024-01-29 16:37 UTC, f-lab-moony commented on src/main/java/com/stoury/config/SecurityConfig.java
> +            ObjectMapper objectMapper = new ObjectMapper();
objectmapper는 나중에 아마 전역으로 설정할 일이 있으실텐데, 설정을 공유해야돼서, 미리 주입 받는걸로 바꾸시는게 좋을 것 같아요 ~

2024-01-29 16:37 UTC, f-lab-moony commented on src/main/java/com/stoury/controller/MemberController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(createdMember);
개인적으로 created는 굳이 구분 안해도 된다고 생각해요
어차피 클라이언트에서도 200, 401, 403 정도만 특정해서 분기하고 나머진 비슷비슷해서 ..

2024-01-30 08:51 UTC, jzakka commented on src/main/java/com/stoury/utils/JwtUtils.java
> +public class JwtUtils {
### 세션
세션은 클라이언트의 상태를 서버가 가지고 사용자에게 세션키를 제공하여 사요자별 상태를 관리합니다.
### JWT
jwt는 토큰 방식으로 사용자 상태를 클라이언트(사용자)가 가지게 됩니다. 서버는 토큰 시크릿으로 사용자 토큰이 유효한지 판별할 수 있습니다.

지금 프로젝트를 REST API로 개발하고 있는데, rest api는 무상태를 지향한다고 해서 jwt를 사용했습니다.

2024-02-01 15:53 UTC, f-lab-moony commented on src/main/java/com/stoury/utils/JwtUtils.java
> +public class JwtUtils {
조금 더 설득력 있는 이유를 찾아보면 좋을 것 같아요 ~

Stateless는 맞는 말이긴 한데, 인증/인가 관련해서는 제외를 하는게 맞지 않나 합니다. 거기다 그런 관점으로 보면 사실 JWT도 동일하게 상태를 가지는것과 마찬가지라서 JWT를 선택한 이유로 조금 적절하지 않은 것 같아요

왜냐면 이미 레디스가 적용 된 상태라, 세션 방식으로 진행을 해도 클러스터링 시의 문제점은 쉽게 해결이 가능한 상태이고, 세션 아이디 외에 부가 정보를 안가지는 세션 방식과 달리 정보를 포함하고 있는 JWT 사용한다면 보안측면에서 손해가 있을텐데, 그런 차이들을 고려해서 선택했다는 걸 설명할 수 있으면 좋을 것 같아요

물론, 이러이러한 차이점이 있다는 걸 알고 고려해 봤으나, 학습목적으로 JWT를 적용하기로 했다 같은 답변이 준비되어도 좋습니다!

2024-02-01 15:53 UTC, f-lab-moony approved these changes
요것도 바로 머지할게요 ~

2024-02-01 15:53 UTC, f-lab-moony commented
어이쿠 충돌이나네요..!

2024-02-02 04:46 UTC, merged