[#22] 피드 컨트롤러
f-lab-edu/Stoury pull request #23
Opened 2024-01-31 17:01 UTC by jzakka

### 기능
- 피드 CRUD를 담당하는 컨트롤러 연결
- 피드 업데이트
  - 업데이트 시, 이미지를 교체할 순 없고, 선택해서 삭제할 수만 있음
- 피드 조회를 제외하면 모두 인증 필요

### 변경점
- 피드 컨트롤러 생성
- 시큐리티 필터체인 수정
- 파일 생성시 uuid로 랜덤문자열을 생성해서 파일 이름에 붙이도록 수정

2024-02-01 16:32 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요!

2024-02-01 16:32 UTC, f-lab-moony commented on src/main/java/com/stoury/controller/FeedController.java
> +        Member writer = memberService.getMemberByEmail(user.getUsername());
컨트롤러에는 로직이 없는게 좋아요 서비스로 한번 감싸주시면 좋을 것 같아요 ~

2024-02-01 16:32 UTC, f-lab-moony commented on src/main/java/com/stoury/controller/FeedController.java
> +    @ExceptionHandler(value = {FeedCreateException.class, FeedUpdateException.class})
이건 공통 설정으로 빼는게 어떨까요 ?

2024-02-01 16:32 UTC, f-lab-moony commented on src/main/java/com/stoury/controller/FeedController.java
> +        if (!feed.getMember().equals(writer)) {
이런건 Feed에 equalsMember를 만들어서 객체 자체에 질의를 던질 수 있게 디자인해주면 좋을 것 같아요 ~

2024-02-01 16:32 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Feed.java
> +        this.textContent = feedUpdateRequest.textContent();
request로 한번에 업데이트 하는거랑 tags 업데이트 분리하는게 어떨까요 ? 어차피 원자성 유지는 서비스의 역할이라 여기서 굳이 별도의 파라미터를 받는 전체 업데이트를 안만들어도 될 것 같아요

2024-02-01 16:32 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Feed.java
> +        for (Integer sequence : feedUpdateRequest.deleteGraphicContentSequence()) {
이 아래 내용 결국 요청으로 온 삭제 대상 컨텐트를 제외 한 새로운 컬렉션으로 업데이트를 하시려는 것 같은데

애초에 요청을 Set으로 받고

```
graphicContents.stream()
.filter(graphicContent -> !feedUpdateRequest.deleteGraphicContentSequence().contains(graphicContent.getSequence()))
.collect(Collectors.toList());
```
이러면 끝나지 않을까요 ? 저기에 Request에다 contains 질의 던질 수 있게 만들어주고 filter 전에 .map(GraphicContent::getSequence) 를 먼저 넣어줘서 다듬어봐도 좋을 것 같아요 ~

2024-02-01 16:32 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Feed.java
> +        for (Integer sequence : feedUpdateRequest.deleteGraphicContentSequence()) {
추가로, 삭제되는 GraphicContent는 따로 처리해줘야 되는 작업 없나요 ? 지금 상태면 그냥 남아있을 것 같아서요 ~

2024-02-02 05:18 UTC, jzakka commented on src/main/java/com/stoury/controller/FeedController.java
> +        Member writer = memberService.getMemberByEmail(user.getUsername());
memberService에서 사용자를 가져와서 feedService.createFeed()로 토스
-> 아예 feedService.createFeed()에서 직접 사용자를 찾아서 처리

이런식으로 바꾸는 게 좋을까요?

2024-02-02 05:38 UTC, jzakka commented on src/main/java/com/stoury/domain/Feed.java
> +        for (Integer sequence : feedUpdateRequest.deleteGraphicContentSequence()) {
graphicCOntent 엔티티는 orphanRemoval이 돼있어서 참조가 끊기면 삭제되게 했습니다.
저장된 파일도 서비스에서 파일 삭제 이벤트를 날리도록 했습니다.

말씀하신 피드백대로 리팩토링 해보겠습니다!🙂

2024-02-02 14:28 UTC, f-lab-moony commented on src/main/java/com/stoury/controller/FeedController.java
> +        Member writer = memberService.getMemberByEmail(user.getUsername());
네네 모든 비즈니스로직은 서비스레이어에 있는게 좋아요 컨트롤러에 로직이 있으면 기능 자체의 결합도가 증가해서요..!

2024-02-02 14:30 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Feed.java
> +        for (Integer sequence : feedUpdateRequest.deleteGraphicContentSequence()) {
오 종속이 걸려있었군요 ..
사실 종속관계를 끊는걸 제안하고싶긴 한데, 일단 설계하신대로 가시죠!

2024-02-02 14:34 UTC, f-lab-moony approved these changes
고생 많으셨습니다 ~
PR 머지하도록 할게요!

2024-02-02 14:34 UTC, f-lab-moony commented on src/main/java/com/stoury/controller/FeedController.java
> +    public ResponseEntity<Object> getFeedsOfTag(@PathVariable String tagName,
리턴 타입 굳이 ResponseEntity로 감쌀필요 없을 것 같아요 ~

2024-02-02 14:34 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Feed.java
> +          0, 2, 4
이거 혹시 sequence 개념이 뭐때문에 필요한걸까요 ?

2024-02-02 14:34 UTC, merged

2024-02-02 15:14 UTC, jzakka commented on src/main/java/com/stoury/domain/Feed.java
> +          0, 2, 4
피드가 보여질 때 이미지 순서대로 보이게 하려고 sequence를 정의했습니다.
![undefined  feed](https://github.com/f-lab-edu/Stoury/assets/105845911/95ca096c-22b8-4c60-b474-40ec03c88ec5)

2024-02-03 14:09 UTC, jzakka commented on src/main/java/com/stoury/controller/FeedController.java
> +        Member writer = memberService.getMemberByEmail(user.getUsername());
컨트롤러메서드에서 `@AuthenticationPrincipal User user`로 인증된 사용자를 얻어오고 있는데, 이게 getUsername()으로 String타입밖에 반환을 안하네요. user는 제가 커스텀으로 정의한 `LoginMember extends UserDetails` 타입이고 얘는 getUsername()으로 사용자 이메일을 반환하도록 했습니다.
전 서비스에서 사용자를 사용자 id로 받고 싶은데,  getUsername()이 사용자 id를 toString()한걸 반환하고 컨트롤러에서 `Long.parseLong(user.getUsername())`으로 건네주는 방식으로 하는 건 어떤가요?