[#25] 피드 위치정보저장
f-lab-edu/Stoury pull request #27
Opened 2024-02-03 05:01 UTC by jzakka

### 목적
- 인기 여행지, 국내외 구분을 위해선 피드 위치정보가 필요
- 피드를 묶어서 동선을 제공하는 기능에서는 피드가 좌표를 가지는 게 좋다고 판단.

### 변경
- 피드테이블에 도시와 국가 컬럼 추가
- Geocoding API를 이용해 좌표 -> 위치정보 가져옴
- 피드가 갓 생성됐을 때에는 위치정보가 undefined로 표기

### 위치정보 저장 과정
1. 피드 저장
2. 이벤트 리스너에게 좌표와 피드 id 던짐
3. 이벤트리스너에서 좌표를 위치정보로 바꾸고 피드의 위치정보 업데이트

2024-02-04 15:30 UTC, f-lab-moony requested changes
고생 많으셨습니다!
피드백 확인 부탁드려요 ~

2024-02-04 15:30 UTC, f-lab-moony commented on src/main/java/com/stoury/dto/feed/FeedResponse.java
> +                           LocationResponse locationResponse,
요 필드명이 키값이 될텐데 Response는 굳이 안붙여도 되지 않을까요 ?

2024-02-04 15:30 UTC, f-lab-moony commented on src/main/java/com/stoury/service/location/GeocodingLocationService.java
> +    private String getCity(GeocodingResult[] results) {
AddressComponentType 만 빼고 다 동일한 내용이라 한번 더 추출할 수 있을 것 같아요 ~

2024-02-04 15:30 UTC, f-lab-moony commented on src/main/java/com/stoury/service/location/GeocodingLocationService.java
> +                .filter(component -> Arrays.asList(component.types).contains(AddressComponentType.LOCALITY))
요거 Arrays.asList보다 Set.of가 좀더 낫지 않을까요 ~?

2024-02-04 15:30 UTC, f-lab-moony commented on src/main/java/com/stoury/service/location/GeocodingLocationService.java
> +        req.setCallback(new PendingResult.Callback<>() {
이거 콜백으로 받아도 괜찮은거 맞나요 ?
피드에 주소 값이 없을 수 있다는 정책이 되는건데, 주소값은 상화님이 하시려는 기능의 핵심이 아닌가 싶어서요 ~

2024-02-04 15:30 UTC, f-lab-moony commented on src/main/java/com/stoury/service/location/GeocodingLocationService.java
> +        req.setCallback(new PendingResult.Callback<>() {
아 그리고 밑에 두 개 정보(COUNTRY, LOCALITY)는 어디에 쓰려고 하시는걸까요 ? 그냥 같은 국가 같은 지역 정도만 있으면 되는게 맞나요 ?

2024-02-04 15:30 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Feed.java
> +    public void updateLocation(String city, String country) {
피드의 위치가 바뀌어도 되나? 하는 의문이 조금 있네요..!

2024-02-05 01:24 UTC, jzakka commented on src/main/java/com/stoury/service/location/GeocodingLocationService.java
> +        req.setCallback(new PendingResult.Callback<>() {
피드 주소(도시, 국가)로 국내외를 구분하고 인기 여행지를 랭킹하려고 합니다. 그리고 피드를 조회할 때도 정보를 제공합니다.

주소값이 api 통신 실패로 잠깐 없을 수 있는데, 좌표는 남아있기 때문에 나중에라도 다시 주소를 얻어올 수 있을 거라고 생각했습니다. 
여행일지를 만들어서 동선을 만드는 기능은 좌표만 있어도 되기 때문에 괜찮을 것 같습니다.

피드를 생성한 직후에 응답피드의 주소가 `UNDEFINED`로 나오긴 하는데 `위치정보검색중` 이런식으로 표시되게 하는 건 어떨까요.

2024-02-05 01:26 UTC, jzakka commented on src/main/java/com/stoury/domain/Feed.java
> +    public void updateLocation(String city, String country) {
비동기 콜백에서 주소를 업데이트할 때 말곤 안쓰이긴 할 건데, 마땅한 방법이 떠오르지 않네요..

2024-02-07 15:03 UTC, f-lab-moony approved these changes
고생 많으셨습니다 ~
PR은 머지 해둘게요 ~

2024-02-07 15:03 UTC, f-lab-moony commented on src/main/java/com/stoury/config/ContextConfiguration.java
> +                .writeTimeout(5, TimeUnit.SECONDS)
write에도 타임아웃이 있네요 ?

2024-02-07 15:03 UTC, f-lab-moony commented on src/main/java/com/stoury/config/ContextConfiguration.java
> +                .maxRetries(5)
요거 너무 많지 않을까요 ? 아 근데 위에 retryTimeout이 인터벌이 맞는지 잘 모르겠군요 ..

2024-02-07 15:03 UTC, f-lab-moony commented on src/main/java/com/stoury/config/ContextConfiguration.java
> +                .connectTimeout(5, TimeUnit.SECONDS)
커넥트 타임아웃 5초는 좀 긴거같아요 최대 2초정도로만 하는게 좋을 것 같습니다

2024-02-07 15:03 UTC, f-lab-moony commented on src/main/java/com/stoury/service/location/GeocodingLocationService.java
> +            Thread.currentThread().interrupt();
요건 왜해주는건가요 ?

2024-02-07 15:03 UTC, merged

2024-02-07 16:17 UTC, jzakka commented on src/main/java/com/stoury/config/ContextConfiguration.java
> +                .writeTimeout(5, TimeUnit.SECONDS)
아, 요청을 보내는 시간에는 timeout을 잘 안 거나요?

2024-02-07 16:19 UTC, jzakka commented on src/main/java/com/stoury/config/ContextConfiguration.java
> +                .maxRetries(5)
```text
Sets the cumulative time limit for which retry-able errors will be retried. Defaults to 60 seconds. Set to zero to retry requests forever.
This operates separately from the count-based maxRetries(Integer).
```
저 시간동안 리트라이를 할 수 있는 것 같습니다.

많다는 게 설정이 많다는 걸까요?아니면 리트라이 수가 많다는 걸까요?

2024-02-07 16:28 UTC, jzakka commented on src/main/java/com/stoury/service/location/GeocodingLocationService.java
> +            Thread.currentThread().interrupt();
InterruptedException을 처리할 때 예외를 전파시키지 않으려면 호출자의 interrupt 플래그를 세팅하는 걸 권장한다고 나와있어서 이렇게 했습니다.