[#26] 인기 여행지 랭킹
f-lab-edu/Stoury pull request #28
Opened 2024-02-03 10:44 UTC by jzakka

- 기준은 피드의 도시, 국가 정보
- 스케줄러가 인기 여행지를 캐시에 업데이트

- 국내여행지면 인기도시 10개를 긁어옴
- 해외여행지면 인기국가 10개를 긁어옴

2024-02-04 15:38 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요 ~

2024-02-04 15:38 UTC, f-lab-moony commented on src/main/java/com/stoury/scheduler/Scheduler.java
> +        eventPublisher.publishEvent(new UpdatePopularDomesticSpots(this));
이거 굳이 이벤트로 처리 할 이유가 있나요 ?

2024-02-04 15:38 UTC, f-lab-moony commented on src/main/java/com/stoury/scheduler/Scheduler.java
> +    public void updatePopularSpotsCache() {
스케줄러로 공유 캐시를 업데이트하는 로직이 있는것도 좀 부자연스러운 것 같네요
인스턴스가 2대 이상이라면 각자의 스케줄러에 의해 각자의 스케줄대로 공유 캐시에 적재를 할텐데, 불필요한 작업이 많이 일어나게 될 것 같기도 하고, 스케일 인/아웃으로 인해 구동시점이 달라지게 되면 원하는 스케줄대로 갱신도 안되게 될 것 같아요

2024-02-05 01:44 UTC, jzakka commented on src/main/java/com/stoury/scheduler/Scheduler.java
> +        eventPublisher.publishEvent(new UpdatePopularDomesticSpots(this));
지금 보니 꼭 이벤트로 할 필요는 없네요
수정하겠습니다😀

2024-02-05 01:50 UTC, jzakka commented on src/main/java/com/stoury/scheduler/Scheduler.java
> +    public void updatePopularSpotsCache() {
그걸 고려하지 못했네요...

그럼 스케줄러가 스프링 외부에 있어야 할 것 같은데 이 부분 좀 더 조사해보겠습니다.

2024-02-07 15:06 UTC, f-lab-moony approved these changes
배치는 슬랙에 답변 남긴대로 한번 다시 생각해보시면 좋을 것 같아요 ~
현재 상황에서 동작에 문제되는 부분은 아니라 일단 머지 해두겠습니다

2024-02-07 15:06 UTC, merged