[#42] 채팅 기능
f-lab-edu/Stoury pull request #43
Opened 2024-02-16 06:48 UTC by jzakka

- 채팅은 1:1 채팅만 지원
- 웹소켓(STOMP프로토콜) 이용
- 채팅방 입장에는 jwt토큰 필요

### 채팅방 입장 플로우
![chatFlow drawio](https://github.com/f-lab-edu/Stoury/assets/105845911/49ef79af-565b-492c-b98b-ae7328b3f17b)

2024-02-16 15:43 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요 !

근데 그냥 던져본 말이긴 한데, 피드백 남긴것처럼 WebsocketSecurity로 해결 안될경우에 SSE 도입해보는 거 괜찮은 방법일 것 같기도 합니다. 메세지 생성을 굳이 소켓으로 연결해놀 필요는 없을 것 같아서..

2024-02-16 15:43 UTC, f-lab-moony commented on src/main/java/com/stoury/config/AuthorizationHeaderFilter.java
> +    AntPathMatcher pathMather = new AntPathMatcher();
접근지정자가 빠져있어요 ~

2024-02-16 15:43 UTC, f-lab-moony commented on src/main/java/com/stoury/config/AuthorizationHeaderFilter.java
> +        if (pathMather.match("/chatRoom/auth/**", httpServletRequest.getServletPath())) {
음 .. 일단 이렇게 써본적이 없어서 위화감이 많이 드는것도 있는 거 같은데요
어찌보면 정 반대의 목표를 지향하는 세션 / jwt 가 같이 쓰인다는것도 애매하고, 토큰에 채팅방 정보가 들어가는것도 잘 이해가 안되네요 ..?
한 유저는 하나의 채팅만 할 수 있는걸까요 ?

일단 지금 생각으론 토큰이 잘못 사용되는 기분이 듭니다

2024-02-16 15:43 UTC, f-lab-moony commented on src/main/java/com/stoury/config/ContextConfiguration.java
> +            name = {"applicationTaskExecutor", "taskExecutor"}
요거 줄바꿈이 약간 이상한거같아요 ?

2024-02-16 15:43 UTC, f-lab-moony commented on src/main/java/com/stoury/config/ContextConfiguration.java
> +    SimpleAsyncTaskExecutor applicationTaskExecutorVirtualThreads(SimpleAsyncTaskExecutorBuilder builder) {
요거 혹시 어디에 쓰려고 만드시는걸까요 ?

2024-02-16 15:43 UTC, f-lab-moony commented on src/main/java/com/stoury/config/security/SecurityConfig.java
> +                        .requestMatchers(new AntPathRequestMatcher("/members", POST.name())).permitAll()
요건 여담인데, 생성자가 계속 보이니 저는 약간 불편한데 .. path와 method 만 받아서 요 역할을 해주는 메서드를 따로 만들어보는건 어떨까요 ?

2024-02-16 15:43 UTC, f-lab-moony commented on src/main/java/com/stoury/config/websocket/MemberIdArgumentResolver.java
> +    public boolean supportsParameter(MethodParameter parameter) {
음 .. 요런거 약간 원래는 필요 없을 것 같은데, 인증 정보를 못 가져와서 jwt를 통해 어거지로 넣으려고 하신 것 같아서 ..
저도 spring으로 웹소켓 잘 안써봐서 될지는 모르겠지만, [WebsocketSecurity](https://docs.spring.io/spring-security/reference/servlet/integrations/websocket.html) 를 적용하면 가져올 수 있지 않을까요 ?

2024-02-16 15:43 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/ChatRoom.java
> +    List<Member> members = new ArrayList<>();
접근지정자가 없어요 ~

2024-02-16 15:43 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/ChatRoom.java
> +    List<Member> members = new ArrayList<>();
요거 맵핑테이블 직접 만들어서 컨트롤하는게 좋지 않을까요 ~?

2024-02-16 15:43 UTC, f-lab-moony commented on src/main/java/com/stoury/service/ChatService.java
> +    public void checkIfRoomMember(Long memberId, Long chatRoomId) {
트랜잭션 지정이 안되어있네요 ~

2024-02-16 15:43 UTC, f-lab-moony commented on src/main/java/com/stoury/service/ChatService.java
> +        Member sender = memberRepository.findById(senderId).orElseThrow(MemberSearchException::new);
sender, receiver 굳이 구분할 필요 없을 것 같은데, findAllByIds로 가져와서 써도 되지 않을까요 ?

2024-02-16 15:43 UTC, f-lab-moony commented on src/main/java/com/stoury/service/ChatService.java
> +        throw new NotAuthorizedException("You're not a member of the chat room.");
개인적으로 if문에서 멤버가 아닐때를 거르고 throw를 얼리리턴 하는게 더 깔끔할 것 같은데 어떻게 생각하시나요 ?

2024-02-16 15:43 UTC, f-lab-moony commented on src/main/java/com/stoury/service/ChatService.java
> +            ChatMessage savedChatMessage = chatMessageRepository.save(chatMessage);
요거 약간 조회만큼이나 많이 호출될 수 있는 메서드로 보이는데, save는 이벤트로 처리하는게 어떨까 싶은 생각이 드네요

2024-02-16 15:43 UTC, f-lab-moony commented on src/main/java/com/stoury/service/ChatService.java
> +            orderThan = LocalDateTime.of(2100, 12, 31, 0, 0, 0);
요 날짜는 무슨의미일까요 ?

2024-02-17 00:41 UTC, jzakka commented on src/main/java/com/stoury/config/ContextConfiguration.java
> +    SimpleAsyncTaskExecutor applicationTaskExecutorVirtualThreads(SimpleAsyncTaskExecutorBuilder builder) {
스프링부트가 원래 가지고 있던 taskExecutor빈을 spring-boot-weboscket-starter의존성을 추가하면 자기 멋대로 다른 빈으로  덮어버리더라고요. 그래서 job에 사용하던 taskExectuor빈을 사용못하게 되서, 직접 빈으로 만들었습니다.

2024-02-17 03:59 UTC, jzakka commented on src/main/java/com/stoury/service/ChatService.java
> +            orderThan = LocalDateTime.of(2100, 12, 31, 0, 0, 0);
orderThan이 null이면 가장 최근의 메시지를 가져오기 위해 최대한의 날짜로 지정했습니다. 
`LocalDateTime.MAX`는 하이버네이트였는지, db였는지 잘못된 값으로 인식하더라고요.

2024-02-18 12:40 UTC, f-lab-moony commented on src/main/java/com/stoury/config/ContextConfiguration.java
> +    SimpleAsyncTaskExecutor applicationTaskExecutorVirtualThreads(SimpleAsyncTaskExecutorBuilder builder) {
아하..! 근데 그러면 오히려 웹소켓이 쓰던 taskExecutor가 잘못 받아지는거 아닐까요 ?
지금은 상관 없겠지만 .. 말씀대로라면 배치에서 사용할 taskExecutor를 따로 정의했어야 하는게 아닌가 하는 생각이 드네요!
그리고 사실 왜 VIRTUAL 조건이 걸려있는지가 더 궁금했었는데, 저거 현재는 사용이 안되는 조건 아닌가요 ?

2024-02-18 12:42 UTC, f-lab-moony commented on src/main/java/com/stoury/service/ChatService.java
> +            orderThan = LocalDateTime.of(2100, 12, 31, 0, 0, 0);
이 서비스가 2100년까지 있을리는 없다는 가정인건가요 ㅋㅋ 보통 최대한이면 9999로 지정하는데 2100이라서 여쭤봤었어요 뭔가 최대값을 의미하는것처럼 안생겨서 ..
참고로 LocalDateTime.MAX는 이후로도 안쓰시는게 좋을 것 같아요. 어디서 조작 조금이라도 잘못 하면 바로 오버플로우가 나버려서 .. 저희 팀에서는 명시적으로 `8999-12-31`을 사용하고 있습니다 ㅋㅋ

2024-02-18 13:27 UTC, f-lab-moony approved these changes
고생 많으셨습니다 ~
크게 피드백 드릴 내용은 없는 것 같고, 질문 주신 내용은 슬랙으로 답변 드렸어요!
요건 머지 하도록 할게요 ~

2024-02-18 13:27 UTC, f-lab-moony commented on src/main/java/com/stoury/config/sse/SseEmitters.java
> +            emitter.send(SseEmitter.event()
요거 메세지 전송 한번 실패하면 바로 유실되는걸까요 ?

2024-02-18 13:27 UTC, merged

2024-02-18 13:29 UTC, jzakka commented on src/main/java/com/stoury/config/ContextConfiguration.java
> +    SimpleAsyncTaskExecutor applicationTaskExecutorVirtualThreads(SimpleAsyncTaskExecutorBuilder builder) {
덮어씌워지지 않게 하려고,  taskExecutor를 빈으로 등록하는 코드를 그대로 복붙한 거라서, 저 애노테이션이 왜 붙는지는 저도 잘 모르겠습니다.


2024-02-19 00:42 UTC, jzakka commented on src/main/java/com/stoury/config/sse/SseEmitters.java
> +            emitter.send(SseEmitter.event()
재전송 로직도 넣어보겠습니다!