[#3] 사용자 검색, 수정, 삭제
f-lab-edu/Stoury pull request #5
Opened 2024-01-12 15:51 UTC by jzakka

### 검색
- 검색 키워드를 %키워드%로 like 검색
- 사용자를 전부 검색한다는 문제가 있음

### 수정
- 이름, 프사 경로, 소개글 수정 가능

### 삭제
- Soft delete

2024-01-13 16:32 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~ 피드백 확인 부탁드려요!

2024-01-13 16:32 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        Member toDelete = memberRepository.findByEmail(Objects.requireNonNull(deleteMemberEmail))
Member의 변수명은 member가 드러나게 정해주는게 좋을 것 같아요 ~

2024-01-13 16:32 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        Member toDelete = memberRepository.findByEmail(Objects.requireNonNull(deleteMemberEmail))
id가 있는데 email로 찾는 이유가 있을까요 ?

2024-01-13 16:32 UTC, f-lab-moony commented on src/main/java/com/stoury/service/MemberService.java
> +@Transactional
개인적으로 전 이런 동작에 영향을 미치는 어노테이션들은 최대한 좁은 스코프로 잡는걸 선호해서 메서드 단위로 정의하는 편인데요
클래스 단위로 선언하면 이게 무슨 트랜잭션을 물고 있는지 계속 올라가서 확인해야돼서 그렇습니다 ~
인터페이스에 선언돼있으니 찾기가 한층 더 힘든 것 같네요..!

2024-01-13 16:32 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        memberRepository.save(toDelete);
save가 없으면 어떻게 동작하나요 ?

2024-01-13 16:32 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        int pageSize = Integer.parseInt(env.getProperty("members.pagesize"));
페이지 사이즈를 환경변수로 관리하려고 한 이유가 있을까요 ?

2024-01-13 16:32 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        Pageable page = PageRequest.of(0, pageSize, Sort.by("username"));
혹시 이 멤버 목록을 보는 기능은 어떻게 쓰이는걸 생각하신걸까요 ~?

2024-01-13 16:32 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        List<Member> foundMembers = memberRepository.findAllByUsernameLikeIgnoreCase("%"+username+"%", page);
이런 조건이면 containing으로 표현할 수도 있을 것 같아요 ~
`like %..%` 같은 쿼리는 어떤 문제가 있을 수 있을까요 ~?

2024-01-13 16:32 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        username = Objects.requireNonNull(username).replaceAll("\\s+", "");
username이 null인경우 어떻게 동작하나요 ?

2024-01-13 16:32 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        username = Objects.requireNonNull(username).replaceAll("\\s+", "");
혹시 공백 제거는 어떤 입력값때문에 하시는걸까요 ?

2024-01-14 01:42 UTC, jzakka commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        Member toDelete = memberRepository.findByEmail(Objects.requireNonNull(deleteMemberEmail))
email도 사용자를 유일 식별하는데 문제가 없을거라고 생각해서 email을 사용했습니다.

삭제할 사용자를 url에서 경로변수로 가져올 때 email로 가져오면 헷갈릴만하네요. (이메일에 .com, .co.kr 이런 거 때문에?)
이 부분은 id로 수정하겠습니다.

2024-01-14 03:22 UTC, jzakka commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        memberRepository.save(toDelete);
save를 하지 않아도 삭제 테스트가 제대로 동작합니다.

2024-01-14 03:29 UTC, jzakka commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        int pageSize = Integer.parseInt(env.getProperty("members.pagesize"));
페이지 크기같은 값을 외부에서 관리할 수 있도록 하는 게 좋을 것 같다고 생각했습니다.

2024-01-14 03:30 UTC, jzakka commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        Pageable page = PageRequest.of(0, pageSize, Sort.by("username"));
사용자의 닉네임으로 사용자를 검색하는 기능에 사용하고자 합니다.

2024-01-14 03:53 UTC, jzakka commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        List<Member> foundMembers = memberRepository.findAllByUsernameLikeIgnoreCase("%"+username+"%", page);
데이터를 전부 조회해서 username을 포함하는 지 확인하는 문제가 있을 수 있고, SQL인젝션에도 취약할 것 같습니다.

이 부분은 다른 방법을 알아보겠습니다.

2024-01-14 03:55 UTC, jzakka commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        username = Objects.requireNonNull(username).replaceAll("\\s+", "");
사용자 이름이 null이면 NPE가 발생합니다.

requireNonNull을 쓰나 안쓰나 NPE가 발생하네요;;

여기서도 NPE를 커스텀 예외로 바꿔보도록 하겠습니다.

2024-01-14 03:59 UTC, jzakka commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        username = Objects.requireNonNull(username).replaceAll("\\s+", "");
예를 들어 입력값이 '     '이면
like %      %가 되서 공백이 들어간 이름을 찾으려고 합니다.

이름에는 공백이 안들어가게 할 거라서 검색어에서도 공백을 없앴습니다.

2024-01-14 05:33 UTC, jzakka commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        List<Member> foundMembers = memberRepository.findAllByUsernameLikeIgnoreCase("%"+username+"%", page);
MySql에서 제공하는 FULLTEXT인덱스를 활용하면 문제를 해결할 수 있을 것 같습니다.

근데 jpa자체에서는 이 기능을 지원하지 않아서 네이티브 쿼리를 날리도록 해야하는데 repository에서 네이티브 쿼리를 사용하도록 하는게 꺼려집니다. 테스트는 h2 인메모리 db이기도 하고요. 
사실 프로젝트가 mysql이 외의 db는 사용하지 않을 예정이니까 네이티브 쿼리를 쓰도록 하고, 테스트에서만 리포지토리를 스텁으로 만들어서 사용하는 게 좋을까요?

2024-01-14 14:35 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        Member toDelete = memberRepository.findByEmail(Objects.requireNonNull(deleteMemberEmail))
네네 그런것도 있고, 애초에 id가 키값이기때문에 id로 받는게 맞을 것 같아요 ~
클라이언트에서 삭제 요청을 보내려면 조회가 먼저 일어나야해서 어차피 가지고 있을거라 클라이언트 입장에서도 아이디가 편할 것 같아요!

2024-01-14 14:37 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        int pageSize = Integer.parseInt(env.getProperty("members.pagesize"));
요건 외부로 보기가 좀 어려울 것 같아요. 어차피 빌드할 때 같이 들어가는 값이고, 프로그램 환경변수로 넘겨준다고 해도 결국 빌드 스크립트를 수정해야 하는거라 상수로 관리하는거랑 다를게 없지 않을까요 ?

참고로, 페이지 사이즈를 동적으로 관리하고싶다면 api 파라미터로 받는게 맞을 것 같아요!

2024-01-14 14:38 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        Pageable page = PageRequest.of(0, pageSize, Sort.by("username"));
닉네임이면 .. 어떻게 표현하느냐에 따라 다를 것 같은데, sns를 구성중이시니까 보통 스크롤로 데이터를 가져오도록 만들어질 것 같은데, more 방식 페이징을 한번 찾아보시면 좋을 것 같아요 ~

2024-01-14 14:49 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        List<Member> foundMembers = memberRepository.findAllByUsernameLikeIgnoreCase("%"+username+"%", page);
음 .. 몇가지 방법이 생각나는건 ..

1. 검색 기능을 앞자리는 맞는 user만 검색되도록 정책을 잡는다
2. test용 db로 mysql을 사용한다
3. 엘라스틱서치를 사용한다

인데 3번은 그냥 써본말이구요, 배보다 배꼽이 더 클테니..
1번은 제일 간단하긴 하겠지만 상화님이 경험을 더 해봐야하니 .. 2번으로 가는게 어떨까요 ? 테스트를 굳이 h2로 할 필요는 없을 것 같아요!

아 그리고 네이티브 쿼리는 지금처럼 지양하시는 모습 좋습니다만, 어쩔 수 없이 써야 할 때도 있으니 답이 안나올 땐 너무 싫어하진 마세요 ㅋㅋ

2024-01-14 14:51 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        username = Objects.requireNonNull(username).replaceAll("\\s+", "");
NPE보다는 어떤 상황인지 메세지를 보여줘야 할 것 같아요!
그리고 매개변수를 재할당해서 쓰는 건 안티패턴이라 새로 정의해주시는게 좋을 것 같습니다 ~

2024-01-14 14:53 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        username = Objects.requireNonNull(username).replaceAll("\\s+", "");
등록시 이름에 공백이 있는경우를 체크하면 공백을 막을 수 있겠지만, 검색에서는 사용자 입장에선 입력과 다른 값을 보게되는거라 .. 그냥 쓰는게 맞지 않을까요 ?
예를 들어 검색창에 `a                b` 라고 입력했는데 `abc`, `bbabc` 이런게 다 나오면 좀 이상할 것 같아요

2024-01-14 14:54 UTC, f-lab-moony approved these changes
고생 많으셨습니다!
코멘트를 남겨 뒀는데 확인 부탁드려요!
PR은 머지 해두도록 할게요 ~

2024-01-14 14:54 UTC, merged

2024-01-15 04:15 UTC, jzakka commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        username = Objects.requireNonNull(username).replaceAll("\\s+", "");
인스타그램은 어떤식으로 나오나 봤는데 
`aaa               bb` 이런식으로 치면 `aaa`와 `bb`를 모두 포함하는 결과가 상단에 뜨고, 둘 중 하나만 포함하는 결과가 주로 아래쪽에 위치하는 것 같습니다.
그 외에도 좀 복잡한 로직이 있는 것 같기도 하고요.

검색에서 사용자 입장에서 입력과 다른 값을 보게 된다는 게 어떤 상황인지 잘 안그려지네요..

2024-01-15 05:35 UTC, jzakka commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        List<Member> foundMembers = memberRepository.findAllByUsernameLikeIgnoreCase("%"+username+"%", page);
조사해보니 fulltext index는 공백을 포함하는 문장에서 효과가 있는 것 같습니다.

저는 사용자이름에 공백을 넣지 않는 걸 가정해서 다른 방법을 더 생각해보겠습니다.

2024-01-15 13:45 UTC, f-lab-moony commented on src/main/java/com/stoury/service/BasicMemberService.java
> +        username = Objects.requireNonNull(username).replaceAll("\\s+", "");
아이디 검색이라, `a b` 로 입력하면 당연히 의도를 가진 입력값일테니 공백이 제거된 응답들이 나오는게 어색하다 생각했는데, 공백의 의도가 토큰 단위일수도 있겠군요. 요렇게 생각하면 결과는 오히려 자연스러운 것 같습니다!

근데 요건 공백을 없애는게 아니라 구분자로 사용하는 것 같은데, 고렇게 접근해보는게 어떨까요 ?