[#51] 배치 모듈 분리
f-lab-edu/Stoury pull request #52
Opened 2024-02-23 08:03 UTC by jzakka

배치 모듈 분리

1. 빌드서버 -> 배치서버로 배치 모듈 jar 전송
2. 배치서버에서 주기적으로 jar 빌드

2024-02-23 16:31 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요!

근데 배치서버에서 주기적으로 jar 빌드는 무슨뜻이에요 ?

2024-02-23 16:31 UTC, f-lab-moony commented on batch/src/main/java/com/stoury/StouryBatchApplication.java
> +        ConfigurableApplicationContext context = springApplication.run(args);
배치 잡 이름이 설정되지 않은 경우 여기서 시스템 종료를 시켜버리는건 어떨까요 ?

2024-02-23 16:31 UTC, f-lab-moony commented on batch/src/test/groovy/com/stoury/BatchTest.groovy
> +        expect:
요거 밑에 검증이 여러 단계로 나뉘어있어서 expect보단 when - then이 맞지 않을까요 ?

2024-02-23 16:31 UTC, f-lab-moony commented on settings.gradle
> +include 'batch'
서브모듈들 이름을 stoury-chats / stoury-batch 처럼 프로젝트 명을 붙여주는게 어떨까요 ? 정렬이 안돼서 보기가 좀 불편한 것 같아요 ~

2024-02-24 01:37 UTC, jzakka commented on batch/src/main/java/com/stoury/StouryBatchApplication.java
> +        ConfigurableApplicationContext context = springApplication.run(args);
그렇게 해도 괜찮긴 한데, 어차피 배치서버에서 배치 잡 이름을 안넣고 빌드를 하진 않을 것 같습니다.
게다가 지금도 배치 잡 다 돌리면 바로 애플리케이션이 종료되는 구조라서요.

2024-02-24 01:39 UTC, jzakka commented on batch/src/main/java/com/stoury/StouryBatchApplication.java
> +        ConfigurableApplicationContext context = springApplication.run(args);
주기적으로 jar 빌드는, 빌드서버에서 배치서버로 건네준 jar를 배치서버가 주기적으로 빌드한다는 의미였습니다. 😀
배치 애플리케이션을 처음 실행할때 돌리도록 하고(`spring.batch.job.enabled=true`)배치 다 돌리면 종료시키도록 하는 플로우입니다.

2024-02-24 14:44 UTC, f-lab-moony commented on batch/src/main/java/com/stoury/StouryBatchApplication.java
> +        ConfigurableApplicationContext context = springApplication.run(args);
>어차피 배치서버에서 배치 잡 이름을 안넣고 빌드를 하진 않을 것 같습니다.
어차피 빈을 못찾아서 크게 문제가 되진 않겠지만 .. 빈을 못찾았다 는 에러랑 명시적으로 job 이름이 설정되지 않았다고 말해주는거랑 좀 차이가 있지 않을까 하는 생각이 듭니다.

그리고 이건 인풋이 잘못됐을 때 어떻게 할까? 에 대한 방어로직을 말씀드린거여서 그렇게 빌드를 하진 않을 것 같다는 가정은 적절치 않은 것 같아요

> 지금도 배치 잡 다 돌리면 바로 애플리케이션이 종료되는 구조

요건 혹시 무슨 의미일까요 ? 잡을 수행하고 종료되는거랑 인풋에 대한 검사랑 어떤 연관이 있는지 잘 이해가 안돼서 어떻게 생각하신건지 궁금하네요 ~

아 추가로, 지금 잡 이름을 contains로 검사하고 있는데, 이름이 일부만 같은 잡이 등록되면 잘못 수행되게 될 가능성이 있지 않을까요 ? 명시적으로 정해진 이름일 때만 수행되게 조건을 바꾸는건 어떨까 싶습니다 ~

2024-02-24 14:45 UTC, f-lab-moony commented on batch/src/main/java/com/stoury/StouryBatchApplication.java
> +        ConfigurableApplicationContext context = springApplication.run(args);
>주기적으로 jar 빌드는, 빌드서버에서 배치서버로 건네준 jar를 배치서버가 주기적으로 빌드한다는 의미였습니다. 😀
배치 애플리케이션을 처음 실행할때 돌리도록 하고(spring.batch.job.enabled=true)배치 다 돌리면 종료시키도록 하는 플로우입니다.

요건 약간 여전히 이해가 안되는데 .. jar를 왜 주기적으로 빌드를 해야하는걸까요 ?

2024-02-24 14:48 UTC, f-lab-moony approved these changes
고생 많으셨습니다!
PR은 머지 해둘게요 ~

2024-02-24 14:49 UTC, merged

2024-02-25 04:06 UTC, jzakka commented on batch/src/main/java/com/stoury/StouryBatchApplication.java
> +        ConfigurableApplicationContext context = springApplication.run(args);
> 아 추가로, 지금 잡 이름을 contains로 검사하고 있는데, 이름이 일부만 같은 잡이 등록되면 잘못 수행되게 될 가능성이 있지 않을까요 ? 명시적으로 정해진 이름일 때만 수행되게 조건을 바꾸는건 어떨까 싶습니다 ~

통합 테스트때문에 모든 잡을 다 빈으로 등록하고 싶어서 이렇게 했는데, 저도 정해진 이름일 때만 하는 게 좋다고 생각합니다. 이렇게 동작하도록 한번 해보겠습니다.

> 요건 약간 여전히 이해가 안되는데 .. jar를 왜 주기적으로 빌드를 해야하는걸까요 ?

제가 제대로 구현한 게 맞는지 모르겠는데, 스프링 배치 애플리케이션은 일반 WAS랑 달리 실행시키고 작업하고 종료하는 과정으로 동작하는 걸로 이해했습니다.
설명을 잘못 했는데, jar을 주기적으로 빌드 시키는 게 아니고 실행시키는 거였어요ㅎㅎ. 

정리를 좀 하면,
1. 처음 실행시킬 때, 어떤 잡 실행시킬지 파라미터 넣어줌 
2. 배치 애플리케이션이 파라미터보고 실행시킬 잡만 돌림
3. 다 돌리면 종료

이런 과정입니다. 그래서 배치 잡이 파라미터 인풋으로 들어가지 않는 케이스여도 해당 잡을 실행하지 않고 바로 종료할 테니까, 굳이 검사를 할 필요가 있는가 싶은 의견이었습니다!

2024-02-25 05:33 UTC, f-lab-moony commented on batch/src/main/java/com/stoury/StouryBatchApplication.java
> +        ConfigurableApplicationContext context = springApplication.run(args);
아하 이해했습니다!

다른 잡이 실행된다던지 하는 문제는 없겠지만, 배치가 수행됐는데 돌아갈 잡이 없으니 일단 정상적이지 못한 상황인건 동일할 것 같아요. 이럴 때 로그를 보고 조치를 취해야 할텐데 그 로그에 빈을 찾을 수 없다는 예외가 있는것 보다 job 이름이 설정되지 않았다고 명시적으로 나타내는게 좋지 않을까 하는 의견이었습니다 ~

2024-02-25 05:34 UTC, f-lab-moony commented on batch/src/main/java/com/stoury/StouryBatchApplication.java
> +        ConfigurableApplicationContext context = springApplication.run(args);
라고 쓰고 나니 빈을 찾을 수 없다는 예외도 없이 그냥 성공처리하는거 아닌가? 싶은 생각도 드네요 ?

2024-02-25 05:40 UTC, jzakka commented on batch/src/main/java/com/stoury/StouryBatchApplication.java
> +        ConfigurableApplicationContext context = springApplication.run(args);
배치 실행시 
```
===Batch start===
input job name: ${job.name}
Job run: ${job.name}
Job complete: ${job.name}
# 혹은 아무런 잡이 없었다면 No job to run
===Batch end===
```
이런식으로 로그를 출력하게 하는 건 어떨까요