[#4] 피드 생성
f-lab-edu/Stoury pull request #6
Opened 2024-01-16 05:54 UTC by jzakka

- 피드 입력 폼과, 이미지를 받아서 피드로 생성

1. 이미지를 저장
2. 저장경로와 피드 입력데이터 피드 생성

2에서 문제 생기면 1에서 저장했던 이미지도 취소

2024-01-17 16:21 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~ 피드백 확인 부탁드려요!

2024-01-17 16:21 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Feed.java
> +    @BatchSize(size = 10)
이건 혹시 어떤 효과를 얻으려고 쓰신걸까요 ?

2024-01-17 16:21 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/GraphicContent.java
> +    @ManyToOne
혹시 양방향 관계가 필요한 이유가 있을까요 ?

2024-01-17 16:21 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/GraphicContent.java
> +        tempGraphic.path = PATH_PREFIX + LocalDateTime.now().getNano();
얘네 생성자로 넘겨줘도 되지 않을까요 ?

2024-01-17 16:21 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Member.java
> +    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL, mappedBy = "member")
여긴 왜 EAGER일까요 ?

2024-01-17 16:21 UTC, f-lab-moony commented on src/main/java/com/stoury/repository/MemberRepository.java
> +    Slice<Member> findAllByUsername(String username, Pageable page);
요거 메서드명을 조금 더 생각해보는게 어떨까요 ? findBy 는 보통 where a = b 쿼리를 생각해서 헷갈릴 수 있을 것 같아요

2024-01-17 16:21 UTC, f-lab-moony commented on src/main/java/com/stoury/service/FeedService.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
요건 REQUIRES_NEW가 아니어도 되지 않나요 ?

2024-01-17 16:21 UTC, f-lab-moony commented on src/main/java/com/stoury/service/FeedService.java
> +        List<GraphicContent> reservedContents = IntStream.range(0, graphicContents.size())
왜 reserved일까요 ?

2024-01-17 16:21 UTC, f-lab-moony commented on src/main/java/com/stoury/service/FeedService.java
> +        if (Objects.requireNonNull(graphicContents).isEmpty()) {
requireNonNull은 NullPointer에 메세지를 넣는 용도로 쓰는건데, 요렇게 분기하실거면 굳이 requireNonNull을 안써도 될 것 같아요 ~

2024-01-17 16:21 UTC, f-lab-moony commented on src/main/java/com/stoury/event/FileEventListener.java
> +    @TransactionalEventListener
`TransactionPhase.AFTER_COMMIT` 요 속성도 지정하면 어떨까요 ?

2024-01-17 16:21 UTC, f-lab-moony commented on src/test/java/com/stoury/service/FeedServiceTest.java
> +@SpringBootTest
SpringBootTest는 테스트 속도가 상당히 느려서 나중에 테스트 개수가 많아지면 엄청 오래걸리게 될거에요
왠만하면 컨트롤러 테스트나 리파지토리 테스트처럼 꼭 필요한 경우가 아니면 Mock을 통해 유닛 테스트로 만들어주시는게 좋을 것 같아요

2024-01-17 16:21 UTC, f-lab-moony commented on src/test/java/com/stoury/service/FeedServiceTest.java
> +        assertThat(eventCount).isEqualTo(graphicContents.size());
요거 이렇게 eventCount를 측정하기보단 퍼블리셔를 Mocking 해서 publishEvent 호출 횟수를 보는게 더 좋을 것 같습니다

2024-01-20 12:17 UTC, jzakka commented on src/main/java/com/stoury/domain/Feed.java
> +    @BatchSize(size = 10)
createdAt은 피드의 생성날짜를 저장하려고 정의했습니다.

batchSize는 여기서 필요가 없을 것 같은데 정신없이 작업하다가 쓴 것 같네요

2024-01-20 12:17 UTC, jzakka commented on src/main/java/com/stoury/domain/GraphicContent.java
> +    @ManyToOne
피드 하나에 여러개의 사진(혹은 영상)을 올릴 수 있게 하려고 양방향 관계로 설정했습니다.

2024-01-20 12:20 UTC, jzakka commented on src/main/java/com/stoury/domain/Member.java
> +    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL, mappedBy = "member")
앗.. LAZY를 했어야하는데 제가 제대로 확인을 안했군요..

2024-01-20 12:25 UTC, jzakka commented on src/main/java/com/stoury/service/FeedService.java
> +        List<GraphicContent> reservedContents = IntStream.range(0, graphicContents.size())
GraphicContent 엔티티 리스트를 만드는 시점에는 아직 실제로 이미지가 파일시스템에 저장되지는 않고 저장할 경로만 지정돼있어서 reserved라고 했습니다.

2024-01-20 12:31 UTC, jzakka commented on src/main/java/com/stoury/event/FileEventListener.java
> +    @TransactionalEventListener
찾아보니 default가 AFTER_COMMIT인데 명시성을 위해 지정하는 게 좋을까요?

2024-01-24 13:43 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/GraphicContent.java
> +    @ManyToOne
사진은 피드에 연관관계 설정이 안되어 있어도 되지 않을까요 ?

2024-01-24 13:46 UTC, f-lab-moony commented on src/main/java/com/stoury/event/FileEventListener.java
> +    @TransactionalEventListener
넵 디폴트 값이 있어도 명시해주면 좋을 것 같아요! 정해진 건 아니고 상황마다 다르긴 한데, 되게 보편적인 경우를 제외하면 보통 명시되어 있지 않은 경우 항상 코드리뷰때 이 옵션은 왜 안넣으신걸까요 ~? 아 디폴트가 그거라 안넣었습니다 라는 얘기가 나오게 되는 것 같더라구요

2024-01-24 13:46 UTC, f-lab-moony approved these changes
고생 많으셨습니다! 머지하도록 할게요 ~

2024-01-24 13:46 UTC, merged