[#65] 댓글 리스트 조회 성능 개선
f-lab-edu/Stoury pull request #66
Opened 2024-03-13 04:08 UTC by jzakka

- 댓글 리스트 조회 성능 테스트 시 응답시간이 초 단위로 매우 안좋은 걸 확인
- 각 댓글마다 대댓글을 가지는지 확인하는 쿼리가 나감. N+1문제
- 하나의 쿼리에서 각 댓글마다 대댓글도 같이 가져오도록 수정.

2024-03-15 12:42 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 한번 부탁드려요 ~

2024-03-15 12:42 UTC, f-lab-moony commented on src/main/java/com/stoury/dto/comment/CommentResponse.java
>  public record CommentResponse(Long id, SimpleMemberResponse writer, Long feedId,
파라미터 많은경우는 한 줄에 하나씩 넣어주는게 더 가독성이 좋을 것 같아요 ~

2024-03-15 12:42 UTC, f-lab-moony commented on src/main/java/com/stoury/repository/CommentRepository.java
> +            CASE WHEN (SELECT COUNT(nc) FROM Comment nc WHERE nc.parentComment = c) > 0 THEN true ELSE false END )
스칼라 서브쿼리 대신 인라인 뷰로 조인을 거는게 낫지 않을까요 ? 요거 약간 뭔가 억지로 만드는 느낌인데 query dsl로 가능하지 않을까 싶습니다.

추가로, 이거 대댓글의 유무만 필요한거라면 그냥 대댓글 달릴 때 세팅할 수 있는 필드를 하나 두는게 더 낫진 않을까 싶네요?

2024-03-15 14:05 UTC, jzakka commented on src/main/java/com/stoury/repository/CommentRepository.java
> +            CASE WHEN (SELECT COUNT(nc) FROM Comment nc WHERE nc.parentComment = c) > 0 THEN true ELSE false END )
테이블에 논리적 중복이 있어도 대댓글 소유 여부 필드가 있는 게 나을 것 같네요.

쿼리 dsl도 나중에 한 번 적용해보겠습니다

2024-03-17 12:16 UTC, f-lab-moony approved these changes
고생 많으셨습니다 ~ 요건 머지 해둘게요 ~

2024-03-17 12:17 UTC, merged