[#72] 쿼리 Dsl 도입
f-lab-edu/Stoury pull request #74
Opened 2024-04-06 05:13 UTC by jzakka

- 쿼리 dsl로 리포지토리 재작성
- 일부 테스트 수정
- 엔티티의 createdAt을 DB가 저장하도록 수정
  - JPAAuditing을 하니까, createdAt이 더 빠른데도 id는 더 느린 상황이 생겨서, createdAt도 DB에게 위임
- COMMENT 테이블 수정
  - 댓글과 대댓글이 섞여있는 COMMENT에서 대댓글만 CHILD_COMMENT테이블로 분리
  - 댓글 조회 과정에서 여러 인덱스가 같이 쓰이면서 왜인지 성능이 안좋았음. 
  - 테이블 분리시키고 COMMENT에서 PARENT_COMMENT_ID 삭제하니 성능 향상.

2024-04-06 08:26 UTC, f-lab-moony requested changes
고생 많으셨습니다!
피드백을 좀 남겨 두었는데 확인 부탁드려요 ~

2024-04-06 08:26 UTC, f-lab-moony commented on Stoury-batch/src/test/groovy/com/stoury/BatchTest.groovy
> +import com.stoury.domain.*
사소한 팁이지만, import 시 *로 하면 유지보수시에 생각지 못한 기능을 참조하게 되는 경우가 생겨서 사용하려는 클래스를 명확하게 지정해주는 게 좋아요. 저희 팀 내에서는 그래서 *가 안쓰이도록 IDE 설정을 조절해주고 있어요

2024-04-06 08:26 UTC, f-lab-moony commented on Stoury-chats/src/main/java/com/stoury/domain/ChatMessage.java
> +@DynamicInsert
요거 추가하신 이유가 있을까요 ?

2024-04-06 08:26 UTC, f-lab-moony commented on Stoury-chats/src/main/java/com/stoury/repository/ChatMessageRepository.java
> +    public List<ChatMessage> saveAll(List<ChatMessage> saveChatMessages) {
이건 혹시 queryDsl을 쓰느라 직접 em을 사용하신걸까요 ?

2024-04-06 08:26 UTC, f-lab-moony commented on Stoury-chats/src/main/java/com/stoury/repository/ChatMessageRepository.java
> +public class ChatMessageRepository {
기존처럼 JPARepository 사용하면서 커스텀한 내용을 따로 선언할 수 있어요.
지금같은 경우라면 `ChatMessageRepository extends JPARepository<> implements ChatMessageRepositoryCustom`
처럼 선언하고, ChatMessageRepositoryCustom 인터페이스와 ChatMessageRepositoryCumtomImpl 구현체를 만들면 가능합니다.

2024-04-06 08:26 UTC, f-lab-moony commented on src/main/java/com/stoury/repository/ChildCommentRepository.java
> +    public Optional<ChildComment> findById(Long id) {
요거는 readOnly를 안해도 되나요 ?
사실 전 이런 부분때문에 클래스에 `@Transactional` 붙이는 걸 선호하지 않는데요, 어노테이션이 안붙어있을 때 진짜 안붙은건지 클래스에 기본값이 있는지를 매번 확인해줘야되고, 무의식적으로 클래스에 붙었겠거니 하고 잘못 설정하는경우가 더 많았던 것 같아요

2024-04-06 08:26 UTC, f-lab-moony commented on src/main/java/com/stoury/repository/FeedRepository.java
> +    private final JPAQueryFactory jpaQueryFactory;
뭔가 다 이렇게 바뀌었군요 ㅋㅋ QueryDSL을 쓴다고 기존의 쿼리메서드를 사용 못하는게 아니라서 위에 코멘트 한번 확인해보시면 좋을 것 같아요 ~

2024-04-06 08:28 UTC, f-lab-moony commented
>JPAAuditing을 하니까, createdAt이 더 빠른데도 id는 더 느린 상황이 생겨서, createdAt도 DB에게 위임

이런 이슈가 있군요 ?

>COMMENT 테이블 수정
>댓글과 대댓글이 섞여있는 COMMENT에서 대댓글만 CHILD_COMMENT테이블로 분리
>댓글 조회 과정에서 여러 인덱스가 같이 쓰이면서 왜인지 성능이 안좋았음.
>테이블 분리시키고 COMMENT에서 PARENT_COMMENT_ID 삭제하니 성능 향상.

이건 왠지 대댓글들 Parent_comment_id 가 분포도가 굉장히 낮았던게 아닌가 하는 생각이 드네요?

2024-04-06 12:41 UTC, jzakka commented on Stoury-chats/src/main/java/com/stoury/domain/ChatMessage.java
> +@DynamicInsert
JPA에서 기본적으로 설정되지 않은 필드는 null로 설정하고 쿼리를 날리더라고요.
저같은 경우는 createdAt을 MySql이 default CURRENT_TIMESTAMP로 설정하게 하고 싶은데 `@DynamicInsert`가 안붙으면

```sql
INSERT INTO COMMENT(MEMBER_ID, ... , CREATED_AT)
VALUES(1, ..., NULL)
```
이렇게 들어가서 `CREATED_AT`이 삽입시점 시간이 아닌 `NULL`로 들어갑니다.

그래서 `NULL`인 필드는 삽입에서 아예 제외시켜서 default 값들이 들어가게 하려고 붙였습니다.
```sql
INSERT INTO COMMENT(MEMBER_ID, ... )
VALUES(1, ...)
-- 처음부터 아예 제외시키고 삽입
```

2024-04-06 12:41 UTC, jzakka commented on Stoury-chats/src/main/java/com/stoury/repository/ChatMessageRepository.java
> +    public List<ChatMessage> saveAll(List<ChatMessage> saveChatMessages) {
네 맞습니다

2024-04-06 12:51 UTC, jzakka commented on Stoury-chats/src/main/java/com/stoury/repository/ChatMessageRepository.java
> +public class ChatMessageRepository {
다른 테크블로그 글을 참고해서 작성한 코드인데 거기선 필요한 파일들이 많아져서 JPAQueryFactory만 주입해서 사용하더라고요. 근데 이 방식으로 하자니 save(), findById() 이런거까지 일일이 구현해야 해서 어느 방법이 더 좋은 지 잘 모르겠습니다.

일단 리포지토리로서의 기능은 잘 작동하고 있는데 이대로 가도 좋을까요? 이미 지웠던 리포지토리 interface를 다시 만들고 하자니 좀 번거로워서요...

2024-04-06 12:52 UTC, jzakka commented on Stoury-chats/src/main/java/com/stoury/repository/ChatMessageRepository.java
> +public class ChatMessageRepository {
유지보수성에 문제가 생길수 있는 구조라면 수정하겠습니다🙏

2024-04-06 12:56 UTC, jzakka commented
> > JPAAuditing을 하니까, createdAt이 더 빠른데도 id는 더 느린 상황이 생겨서, createdAt도 DB에게 위임
> 
> 이런 이슈가 있군요 ?
> 
> > COMMENT 테이블 수정
> > 댓글과 대댓글이 섞여있는 COMMENT에서 대댓글만 CHILD_COMMENT테이블로 분리
> > 댓글 조회 과정에서 여러 인덱스가 같이 쓰이면서 왜인지 성능이 안좋았음.
> > 테이블 분리시키고 COMMENT에서 PARENT_COMMENT_ID 삭제하니 성능 향상.
> 
> 이건 왠지 대댓글들 Parent_comment_id 가 분포도가 굉장히 낮았던게 아닌가 하는 생각이 드네요?

네, 전체 댓글 중 parent_comment_id가 null인 것(즉 부모댓글인 것)이 90프로고 나머지는 전부 하나의 댓글의 대댓글들이었습니다. 
인덱스에 대해 깊은 지식이 없어서 그런지 explain을 봐도 뭐가 문제인지 감을 못잡겠어서 아예 엔티티를 분리했더니 말끔하게 해결됬네요.

근데 또 피드 리스트 조회에서도 성능이 또 이상하군요. 이것도 인덱스 관련된 것 같은데ㅎㅎ

2024-04-08 12:23 UTC, f-lab-moony commented on Stoury-chats/src/main/java/com/stoury/repository/ChatMessageRepository.java
> +public class ChatMessageRepository {
JPARepository의 기본기능과 쿼리메서드는 상당히 편리하고 강력한 기능이라 그걸 포기하는건 좀 아닌 것 같아요. 제가 말씀드린 방법은 현재 구현하신 부분도 같이 사용할 수 있는 부분이라 굳이 디메리트를 안고 가야 할 이유가 없어보입니다

2024-04-08 12:25 UTC, f-lab-moony approved these changes
고생 많으셨습니다!
이번 PR은 일단 여기서 끊고 머지 해 둘게요!

2024-04-08 12:25 UTC, f-lab-moony commented on src/main/java/com/stoury/projection/FeedResponseEntity.java
> +public class FeedResponseEntity {
👍  이 귀찮은걸 해내시다니 ..

2024-04-08 12:25 UTC, merged