[#7] 파일 저장 서비스 구현
f-lab-edu/Stoury pull request #8
Opened 2024-01-18 05:08 UTC by jzakka

- 지정된 경로로 파일을 저장하는 기능

2024-01-19 13:52 UTC, f-lab-moony requested changes
고생 많으셨습니다!
피드백 확인 부탁드려요 ~

2024-01-19 13:52 UTC, f-lab-moony commented on src/main/java/com/stoury/domain/Member.java
> +    List<Feed> feeds = new ArrayList<>();
접근지정자가 빠졌네요 ~

2024-01-19 13:52 UTC, f-lab-moony commented on src/main/java/com/stoury/utils/FileUtils.java
> +    public enum SupportedFileType {
enum은 따로 정의하는게 어떨까요 ?

2024-01-19 13:52 UTC, f-lab-moony commented on src/main/java/com/stoury/utils/FileUtils.java
> +    public static String getFileNameByCurrentTime() {
이거 지금은 시간만 문자열로 바꿔서 던져주고 있어서 메서드 명이랑 안맞는 것 같은데, 파일이나 파일 이름을 매개변수로 받아서 최종 결과를 리턴해주는게 어떨까요 ?

2024-01-19 13:52 UTC, f-lab-moony commented on src/main/java/com/stoury/utils/FileUtils.java
> +        LocalDateTime nanoLocalDateTime = LocalDateTime.ofInstant(Instant.now(), ZoneId.systemDefault());
요거 `LocalDateTime.now().format()` 을 사용해볼 수 있을 것 같아요

2024-01-19 13:52 UTC, f-lab-moony commented on src/main/java/com/stoury/utils/FileUtils.java
> +    public static SupportedFileType getFileType(MultipartFile file) {
요거 enum 타입을 가져오는거라 이 작업은 enum이 직접 하는게 맞을것같아요

2024-01-19 13:52 UTC, f-lab-moony commented on src/main/java/com/stoury/utils/FileUtils.java
> +        return switch (Objects.requireNonNull(contentType)) {
각 enum 타입에 accept를 정의하고 stream을 이용하면 좀더 확장에 용이한 구조가 될 것 같아요!

2024-01-19 13:52 UTC, f-lab-moony commented on src/main/java/com/stoury/service/StorageService.java
> +public interface StorageService {
요거는 나중에 CDN이나 외부 저장소에 저장할 걸 염두에 두신거겠죠 ?
충분히 대비할 만한 포인트라고 생각하긴 하지만, 추상화는 필요한 시점에 하는게 맞다고도 생각합니다.
개발을 하다보니, 가까운 시일내에 일어날 일이 아니라면 준비 해 놔 봤자 바꿔야되는 경우가 훨씬 많더라구요 요구사항이 내 맘대로 되는게 아니다보니 ..

의도는 좋다고 생각합니다!

2024-01-19 13:52 UTC, f-lab-moony commented on src/main/java/com/stoury/service/FileStorageService.java
> +    public void saveFilesAtPath(Pair<MultipartFile, String> reservedImagePaths) {
근데 요거 굳이 페어로 가지고 다닐 필요 있나요?

2024-01-19 13:52 UTC, f-lab-moony commented on src/main/java/com/stoury/service/FileStorageService.java
> +        String directory = fullPath.substring(0, lastIndexOfSlash);
fullPath에서 자르는거라 어떤 값들이 들어가서 디렉토리 명이 되는지 잘 보이지가 않네요, 경로의 재료가 될 녀석들을 여기까지 던져주고, fullPath는 여기서 만드는게 어떨까요 ?

2024-01-20 13:53 UTC, jzakka commented on src/main/java/com/stoury/utils/FileUtils.java
> +    public enum SupportedFileType {
어떤 경우에 내부 클래스를 정의하는 게 좋을 지 감이 잘 안잡히네요..
'논리적으로 연관되는 모듈은 내부클래스로 정의하는 게 좋다'라고 보긴 했는데 연관된다 라는 게 어느 정도를 기준으로 말하는 건지 잘 모르겠습니다.

2024-01-20 13:59 UTC, jzakka commented on src/main/java/com/stoury/utils/FileUtils.java
> +    public static String getFileNameByCurrentTime() {
입력으로 들어오는 파일 이름이 `file1.jpeg`라면 `file1_2024_01_20_123123123.jpeg` 이렇게 만드는 건 어떨까요?
아니면 날짜별로 디렉토리를 만들어서 파일 이름은 피드 id로 만드는 건 어떨까요? (예. `/2024-01-20/feed1_image_1.jpeg`)

2024-01-20 15:44 UTC, jzakka commented on src/main/java/com/stoury/service/StorageService.java
> +public interface StorageService {
그것도 있고, 피드 서비스에서 파일 서비스를 호출하는 부분을 먼저만들고 테스트를 만들었었는데 아직 파일저장을 어떻게 할지 구현을 안했어서 미리 인터페이스로 빼고 테스트용 구체 클래스를 만들었었습니다.

2024-01-20 15:59 UTC, jzakka commented on src/main/java/com/stoury/service/FileStorageService.java
> +        String directory = fullPath.substring(0, lastIndexOfSlash);
제 생각엔 fullPath를 여기서 만들기보단 saveFilesAtPath는 Path에 파일을 저장하는 게 주요 책임이니까 파라미터로 Path 를 받고 단순히 저장만 하도록 바꾸는 게 좋을 것 같기도 합니다.

2024-01-24 13:48 UTC, f-lab-moony commented on src/main/java/com/stoury/utils/FileUtils.java
> +    public enum SupportedFileType {
거의 대부분의 경우 내부 클래스보단 바깥에 두는게 용이합니다. 연관되는 모듈은 패키지로 묶어주면 충분히 응집도를 높일 수 있구요, 저같은경우는 이 `클래스 내부에서만 사용되는 별도의 클래스`가 필요한 경우엔 내부클래스를 고려해보는 편입니다. 바깥에서 사용하게 되면 일단 클래스 사용시 뎁스가 늘어나게 돼서 보기가 굉장히 안좋아진다는 커다란 단점이 있어서요 ..

2024-01-24 13:50 UTC, f-lab-moony commented on src/main/java/com/stoury/utils/FileUtils.java
> +    public static String getFileNameByCurrentTime() {
네네 고런식으로 이름을 받아서 풀패스를 만들어주는 식으로 가면 좋을 것 같아요!
폴더별로 관리하는것도 좋은 방법일 것 같은데, 날짜별로가 괜찮을지는 잘 모르겠네요 어차피 탐색이야 패스로 가는거니까 상관 없는데, 이 파일들을 백업한다던지 정리한다던지 하게되면 날짜별보단 유저별로 관리될거같은 느낌이 들어서..

2024-01-24 13:51 UTC, f-lab-moony commented on src/main/java/com/stoury/service/FileStorageService.java
> +        String directory = fullPath.substring(0, lastIndexOfSlash);
오 그것도 좋은 생각이네요!

2024-01-24 13:54 UTC, f-lab-moony approved these changes
고생 많으셨습니다!
요것도 바로 머지 할게요 ~

2024-01-24 13:54 UTC, f-lab-moony commented on src/main/java/com/stoury/utils/SupportedFileType.java
> +                .filter(fileType -> fileType.getAcceptContentType().equals(contentType))
`getAcceptContentType()` 요거 boolean 반환하는 메서드로 한번 빼면 좀더 객체지향적으로 만들 수 있을 것 같아요

2024-01-24 13:54 UTC, merged

2024-01-24 14:23 UTC, jzakka commented on src/main/java/com/stoury/utils/FileUtils.java
> +    public static String getFileNameByCurrentTime() {
백업을 할 때, 파일을 유저별로 관리하는 게 더 좋은 이유가
이미지가 유실됐을 때, 유저(혹은 피드)별로 경로구분해서 백업해놓으면 원상복구가 가능해서 그런건가요??

백업까지 고려해보진 않았는데 되게 궁금하네요💭